/*
 * Generated by SAP SchemaToJava Generator NW05 on Tue Oct 23 15:26:07 EEST 2007
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.services.webservices.espbase.configuration.p_set;

/**
 * Schema complexType Java representation.
 * Represents type {http://xml.sap.com/2006/11/esi/conf/feat/}PropertySetType
 */
public  class PropertySetType implements java.io.Serializable,com.sap.engine.services.webservices.jaxrpc.encoding.IdenticObject {

  private static final long serialVersionUID = -917374725140829009L;

  // Attribute field for attribute {}name
  private java.lang.String _a_Name;
  /**
   * Set method for attribute {}name
   */
  public void setName(java.lang.String _Name) {
    this._a_Name = _Name;
  }
  /**
   * Get method for attribute {}name
   */
  public java.lang.String getName() {
    return _a_Name;
  }

  // Element field for element {http://xml.sap.com/2006/11/esi/conf/feat/}subject
  private java.util.ArrayList _f_Subject = new java.util.ArrayList();
  /**
   * Set method for element {http://xml.sap.com/2006/11/esi/conf/feat/}subject
   */
  public void setSubject(com.sap.engine.services.webservices.espbase.configuration.p_set.SubjectType[] _Subject) {
    this._f_Subject.clear();
    if (_Subject != null) {
      for (int i=0; i<_Subject.length; i++) {
        if (_Subject[i] != null)
          this._f_Subject.add(_Subject[i]);
      }
    }
  }
  /**
   * Get method for element {http://xml.sap.com/2006/11/esi/conf/feat/}subject
   */
  public com.sap.engine.services.webservices.espbase.configuration.p_set.SubjectType[] getSubject() {
    com.sap.engine.services.webservices.espbase.configuration.p_set.SubjectType[] result = new com.sap.engine.services.webservices.espbase.configuration.p_set.SubjectType[_f_Subject.size()];
    _f_Subject.toArray(result);
    return result;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof PropertySetType)) return false;
    PropertySetType typed = (PropertySetType) object;
    if (this._a_Name != null) {
      if (typed._a_Name == null) return false;
      if (!this._a_Name.equals(typed._a_Name)) return false;
    } else {
      if (typed._a_Name != null) return false;
    }
    com.sap.engine.services.webservices.espbase.configuration.p_set.SubjectType[] _f_Subject1 = this.getSubject();
    com.sap.engine.services.webservices.espbase.configuration.p_set.SubjectType[] _f_Subject2 = typed.getSubject();
    if (_f_Subject1 != null) {
      if (_f_Subject2 == null) return false;
      if (_f_Subject1.length != _f_Subject2.length) return false;
      for (int i1 = 0; i1 < _f_Subject1.length ; i1++) {
        if (_f_Subject1[i1] != null) {
          if (_f_Subject2[i1] == null) return false;
          if (!_f_Subject1[i1].equals(_f_Subject2[i1])) return false;
        } else {
          if (_f_Subject2[i1] != null) return false;
        }
      }
    } else {
      if (_f_Subject2 != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._a_Name != null) {
      result+= this._a_Name.hashCode();
    }
    com.sap.engine.services.webservices.espbase.configuration.p_set.SubjectType[] _f_Subject1 = this.getSubject();
    if (_f_Subject1 != null) {
      for (int i1 = 0; i1 < _f_Subject1.length ; i1++) {
        if (_f_Subject1[i1] != null) {
          result+= _f_Subject1[i1].hashCode();
        }
      }
    }
    return result;
  }

  public java.lang.String get__ID() {
    return java.lang.String.valueOf(super.hashCode());
  }
}
