/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Nov 30 15:20:54 EET 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.services.webservices.espbase.configuration.soap_app;

/**
 * Schema complexType Java representation.
 * Represents type {http://xml.sap.com/2006/11/esi/conf/soapapplication}ConditionType
 */
public  class ConditionType implements java.io.Serializable {

  private static final long serialVersionUID = 5618742347987792336L;

  // // Active choise field
  private int _c_validField = 0;
  private com.sap.engine.services.webservices.espbase.configuration.soap_app.PListType _f_Properties;
  /**
   * Set method for element {}properties
   */
  public void setProperties(com.sap.engine.services.webservices.espbase.configuration.soap_app.PListType _Properties) {
    if (this._c_validField != 0 && this._c_validField != 1) {
      this.unsetContent();
    }
    this._f_Properties = _Properties;
    this._c_validField = 1;
  }
  /**
   * Get method for element {}properties
   */
  public com.sap.engine.services.webservices.espbase.configuration.soap_app.PListType getProperties() {
    if (this._c_validField != 1) {
      return null;
    }
    return this._f_Properties;
  }
  /**
   * Check method for element {}properties
   */
  public boolean isSetProperties() {
    return (this._c_validField ==1);
  }
  private boolean _f_BooleanValue;
  /**
   * Set method for element {}boolean-value
   */
  public void setBooleanValue(boolean _BooleanValue) {
    if (this._c_validField != 0 && this._c_validField != 2) {
      this.unsetContent();
    }
    this._f_BooleanValue = _BooleanValue;
    this._c_validField = 2;
  }
  /**
   * Get method for element {}boolean-value
   */
  public boolean isBooleanValue() {
    if (this._c_validField != 2) {
      return false;
    }
    return this._f_BooleanValue;
  }
  /**
   * Check method for element {}boolean-value
   */
  public boolean isSetBooleanValue() {
    return (this._c_validField ==2);
  }
  /**
   * Common get method for choice type.
   */
  public java.lang.Object getContent() {
    switch (this._c_validField) {
      case 1: return this.getProperties();
      case 2: return new java.lang.Boolean(this._f_BooleanValue);
    }
    return null;
  }
  /**
   * Returns true if this choice has content set.
   */
  public boolean isSetContent() {
    return (this._c_validField == 0);
  }
  /**
   * Clears choice content.
   */
  public void unsetContent() {
    switch (this._c_validField) {
      case  1: {
        this._f_Properties = null;
        break;
      }
      case  2: {
        this._f_BooleanValue = false;
        break;
      }
    }
    this._c_validField = 0;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof ConditionType)) return false;
    ConditionType typed = (ConditionType) object;
    if (this._c_validField != typed._c_validField) return false;
    switch (this._c_validField) {
      case 1: {
        if (this._f_Properties != null) {
          if (typed._f_Properties == null) return false;
          if (!this._f_Properties.equals(typed._f_Properties)) return false;
        } else {
          if (typed._f_Properties != null) return false;
        }
        break;
      }
      case 2: {
        if (this._f_BooleanValue != typed._f_BooleanValue) return false;
        break;
      }
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    switch (this._c_validField) {
      case 1: {
        if (this._f_Properties != null) {
          result+= this._f_Properties.hashCode();
        }
        result = result * this._c_validField;
        break;
      }
      case 2: {
        if (this._f_BooleanValue) result += 1;
        result = result * this._c_validField;
        break;
      }
    }
    return result;
  }
}
