/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Nov 30 15:20:54 EET 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.services.webservices.espbase.configuration.soap_app;

/**
 * Schema complexType Java representation.
 * Represents type {http://xml.sap.com/2006/11/esi/conf/soapapplication}DependencyType
 */
public  class DependencyType implements java.io.Serializable {
  
  public static final String DT_TO_RT = "DT_TO_RT";
  public static final String TRUE_TO_RT = "TRUE_TO_RT";
  public static final String SINGLE_DT_OP_TO_RT = "SINGLE_DT_OP_TO_RT";
  public static final String DT_OP_TO_RT_OP = "DT_OP_TO_RT_OP";
  public static final String RT_TO_RT = "RT_TO_RT";
    
  private static final long serialVersionUID = -4432724694172267784L;

  // Element field for element {}condition
  private com.sap.engine.services.webservices.espbase.configuration.soap_app.ConditionType _f_Condition;
  /**
   * Set method for element {}condition
   */
  public void setCondition(com.sap.engine.services.webservices.espbase.configuration.soap_app.ConditionType _Condition) {
    this._f_Condition = _Condition;
  }
  /**
   * Get method for element {}condition
   */
  public com.sap.engine.services.webservices.espbase.configuration.soap_app.ConditionType getCondition() {
    return this._f_Condition;
  }

  // Element field for element {}result
  private com.sap.engine.services.webservices.espbase.configuration.soap_app.ConditionResultType _f_Result;
  /**
   * Set method for element {}result
   */
  public void setResult(com.sap.engine.services.webservices.espbase.configuration.soap_app.ConditionResultType _Result) {
    this._f_Result = _Result;
  }
  /**
   * Get method for element {}result
   */
  public com.sap.engine.services.webservices.espbase.configuration.soap_app.ConditionResultType getResult() {
    return this._f_Result;
  }

  // Attribute field for attribute {}type
  private java.lang.String _a_Type;
  /**
   * Set method for attribute {}namespace
   */
  public void setType(java.lang.String _Type) {
    this._a_Type = _Type;
  }
  /**
   * Get method for attribute {}namespace
   */
  public java.lang.String getType() {
    return _a_Type;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof DependencyType)) return false;
    DependencyType typed = (DependencyType) object;
    if (this._f_Condition != null) {
      if (typed._f_Condition == null) return false;
      if (!this._f_Condition.equals(typed._f_Condition)) return false;
    } else {
      if (typed._f_Condition != null) return false;
    }
    if (this._f_Result != null) {
      if (typed._f_Result == null) return false;
      if (!this._f_Result.equals(typed._f_Result)) return false;
    } else {
      if (typed._f_Result != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Condition != null) {
      result+= this._f_Condition.hashCode();
    }
    if (this._f_Result != null) {
      result+= this._f_Result.hashCode();
    }
    return result;
  }
}
