/*
 * Generated by SAP SchemaToJava Generator NW05 on Thu Nov 30 15:20:54 EET 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.services.webservices.espbase.configuration.soap_app;

/**
 * Schema complexType Java representation.
 * Represents type {http://xml.sap.com/2006/11/esi/conf/soapapplication}PType
 */
public  class PType implements java.io.Serializable {

  private static final long serialVersionUID = -2910551171725733715L;

  // Attribute field for attribute {}namespace
  private java.lang.String _a_Namespace;
  /**
   * Set method for attribute {}namespace
   */
  public void setNamespace(java.lang.String _Namespace) {
    this._a_Namespace = _Namespace;
  }
  /**
   * Get method for attribute {}namespace
   */
  public java.lang.String getNamespace() {
    return _a_Namespace;
  }

  // Attribute field for attribute {}name
  private java.lang.String _a_Name;
  /**
   * Set method for attribute {}name
   */
  public void setName(java.lang.String _Name) {
    this._a_Name = _Name;
  }
  /**
   * Get method for attribute {}name
   */
  public java.lang.String getName() {
    return _a_Name;
  }

  // Attribute field for attribute {}value
  private java.lang.String _a_Value;
  /**
   * Set method for attribute {}value
   */
  public void setValue(java.lang.String _Value) {
    this._a_Value = _Value;
  }
  /**
   * Get method for attribute {}value
   */
  public java.lang.String getValue() {
    return _a_Value;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof PType)) return false;
    PType typed = (PType) object;
    if (this._a_Namespace != null) {
      if (typed._a_Namespace == null) return false;
      if (!this._a_Namespace.equals(typed._a_Namespace)) return false;
    } else {
      if (typed._a_Namespace != null) return false;
    }
    if (this._a_Name != null) {
      if (typed._a_Name == null) return false;
      if (!this._a_Name.equals(typed._a_Name)) return false;
    } else {
      if (typed._a_Name != null) return false;
    }
    if (this._a_Value != null) {
      if (typed._a_Value == null) return false;
      if (!this._a_Value.equals(typed._a_Value)) return false;
    } else {
      if (typed._a_Value != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._a_Namespace != null) {
      result+= this._a_Namespace.hashCode();
    }
    if (this._a_Name != null) {
      result+= this._a_Name.hashCode();
    }
    if (this._a_Value != null) {
      result+= this._a_Value.hashCode();
    }
    return result;
  }
  @Override
  public String toString() {
    return "{" + this._a_Namespace + "}" + this._a_Name + "='" + this._a_Value + "'";
  }
   
}
