/*
 * Generated by SAP SchemaToJava Generator NW05 on Tue Jun 12 14:57:36 EEST 2007
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.services.webservices.espbase.sr.classifications;

/**
 * Schema complexType Java representation.
 * Represents type {http://www.sap.com/webas/2006/11/sr/classifications}ClassificationType
 */
public  class ClassificationType implements java.io.Serializable {

  private static final long serialVersionUID = 707820296942111010L;

  // Element field for element {http://www.sap.com/webas/2006/11/sr/classifications}qname
  private javax.xml.namespace.QName _f_Qname;
  /**
   * Set method for element {http://www.sap.com/webas/2006/11/sr/classifications}qname
   */
  public void setQname(javax.xml.namespace.QName _Qname) {
    this._f_Qname = _Qname;
  }
  /**
   * Get method for element {http://www.sap.com/webas/2006/11/sr/classifications}qname
   */
  public javax.xml.namespace.QName getQname() {
    return this._f_Qname;
  }

  // Element field for element {http://www.sap.com/webas/2006/11/sr/classifications}code
  private java.lang.String _f_Code;
  /**
   * Set method for element {http://www.sap.com/webas/2006/11/sr/classifications}code
   */
  public void setCode(java.lang.String _Code) {
    this._f_Code = _Code;
  }
  /**
   * Get method for element {http://www.sap.com/webas/2006/11/sr/classifications}code
   */
  public java.lang.String getCode() {
    return this._f_Code;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof ClassificationType)) return false;
    ClassificationType typed = (ClassificationType) object;
    if (this._f_Qname != null) {
      if (typed._f_Qname == null) return false;
      if (!this._f_Qname.equals(typed._f_Qname)) return false;
    } else {
      if (typed._f_Qname != null) return false;
    }
    if (this._f_Code != null) {
      if (typed._f_Code == null) return false;
      if (!this._f_Code.equals(typed._f_Code)) return false;
    } else {
      if (typed._f_Code != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Qname != null) {
      result+= this._f_Qname.hashCode();
    }
    if (this._f_Code != null) {
      result+= this._f_Code.hashCode();
    }
    return result;
  }
}
