/*
 * Generated by SAP SchemaToJava Generator NW05 on Tue Aug 28 15:48:13 EEST 2007
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.services.webservices.espbase.sr.classifications;

/**
 * Schema complexType Java representation.
 * Represents type {http://www.sap.com/webas/2006/11/sr/classifications}RootClassificationType
 */
public  class RootClassificationType implements java.io.Serializable {

  private static final long serialVersionUID = 6202535926015972838L;

  // Attribute field for attribute {}sapClassifications
  private boolean _a_SapClassifications = true;
  /**
   * Set method for attribute {}sapClassifications
   */
  public void setSapClassifications(boolean _SapClassifications) {
    this._a_SapClassifications = _SapClassifications;
  }
  /**
   * Get method for attribute {}sapClassifications
   */
  public boolean isSapClassifications() {
    return _a_SapClassifications;
  }

  // Element field for element {http://www.sap.com/webas/2006/11/sr/classifications}Classification
  private java.util.ArrayList _f_Classification = new java.util.ArrayList();
  /**
   * Set method for element {http://www.sap.com/webas/2006/11/sr/classifications}Classification
   */
  public void setClassification(com.sap.engine.services.webservices.espbase.sr.classifications.ClassificationType[] _Classification) {
    this._f_Classification.clear();
    if (_Classification != null) {
      for (int i=0; i<_Classification.length; i++) {
        if (_Classification[i] != null)
          this._f_Classification.add(_Classification[i]);
      }
    }
  }
  /**
   * Get method for element {http://www.sap.com/webas/2006/11/sr/classifications}Classification
   */
  public com.sap.engine.services.webservices.espbase.sr.classifications.ClassificationType[] getClassification() {
    com.sap.engine.services.webservices.espbase.sr.classifications.ClassificationType[] result = new com.sap.engine.services.webservices.espbase.sr.classifications.ClassificationType[_f_Classification.size()];
    _f_Classification.toArray(result);
    return result;
  }

  // Element field for element {http://www.sap.com/webas/2006/11/sr/classifications}GroupClassification
  private java.util.ArrayList _f_GroupClassification = new java.util.ArrayList();
  /**
   * Set method for element {http://www.sap.com/webas/2006/11/sr/classifications}GroupClassification
   */
  public void setGroupClassification(com.sap.engine.services.webservices.espbase.sr.classifications.GroupClassificationType[] _GroupClassification) {
    this._f_GroupClassification.clear();
    if (_GroupClassification != null) {
      for (int i=0; i<_GroupClassification.length; i++) {
        if (_GroupClassification[i] != null)
          this._f_GroupClassification.add(_GroupClassification[i]);
      }
    }
  }
  /**
   * Get method for element {http://www.sap.com/webas/2006/11/sr/classifications}GroupClassification
   */
  public com.sap.engine.services.webservices.espbase.sr.classifications.GroupClassificationType[] getGroupClassification() {
    com.sap.engine.services.webservices.espbase.sr.classifications.GroupClassificationType[] result = new com.sap.engine.services.webservices.espbase.sr.classifications.GroupClassificationType[_f_GroupClassification.size()];
    _f_GroupClassification.toArray(result);
    return result;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof RootClassificationType)) return false;
    RootClassificationType typed = (RootClassificationType) object;
    if (this._a_SapClassifications != typed._a_SapClassifications) return false;
    com.sap.engine.services.webservices.espbase.sr.classifications.ClassificationType[] _f_Classification1 = this.getClassification();
    com.sap.engine.services.webservices.espbase.sr.classifications.ClassificationType[] _f_Classification2 = typed.getClassification();
    if (_f_Classification1 != null) {
      if (_f_Classification2 == null) return false;
      if (_f_Classification1.length != _f_Classification2.length) return false;
      for (int i1 = 0; i1 < _f_Classification1.length ; i1++) {
        if (_f_Classification1[i1] != null) {
          if (_f_Classification2[i1] == null) return false;
          if (!_f_Classification1[i1].equals(_f_Classification2[i1])) return false;
        } else {
          if (_f_Classification2[i1] != null) return false;
        }
      }
    } else {
      if (_f_Classification2 != null) return false;
    }
    com.sap.engine.services.webservices.espbase.sr.classifications.GroupClassificationType[] _f_GroupClassification1 = this.getGroupClassification();
    com.sap.engine.services.webservices.espbase.sr.classifications.GroupClassificationType[] _f_GroupClassification2 = typed.getGroupClassification();
    if (_f_GroupClassification1 != null) {
      if (_f_GroupClassification2 == null) return false;
      if (_f_GroupClassification1.length != _f_GroupClassification2.length) return false;
      for (int i1 = 0; i1 < _f_GroupClassification1.length ; i1++) {
        if (_f_GroupClassification1[i1] != null) {
          if (_f_GroupClassification2[i1] == null) return false;
          if (!_f_GroupClassification1[i1].equals(_f_GroupClassification2[i1])) return false;
        } else {
          if (_f_GroupClassification2[i1] != null) return false;
        }
      }
    } else {
      if (_f_GroupClassification2 != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._a_SapClassifications) result += 1;
    com.sap.engine.services.webservices.espbase.sr.classifications.ClassificationType[] _f_Classification1 = this.getClassification();
    if (_f_Classification1 != null) {
      for (int i1 = 0; i1 < _f_Classification1.length ; i1++) {
        if (_f_Classification1[i1] != null) {
          result+= _f_Classification1[i1].hashCode();
        }
      }
    }
    com.sap.engine.services.webservices.espbase.sr.classifications.GroupClassificationType[] _f_GroupClassification1 = this.getGroupClassification();
    if (_f_GroupClassification1 != null) {
      for (int i1 = 0; i1 < _f_GroupClassification1.length ; i1++) {
        if (_f_GroupClassification1[i1] != null) {
          result+= _f_GroupClassification1[i1].hashCode();
        }
      }
    }
    return result;
  }
}
