/*
 * Generated by SAP SchemaToJava Generator NW05 on Tue Feb 22 14:02:04 EET 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.services.webservices.espbase.configuration;

/**
 * Schema complexType Java representation.
 * Represents type {http://www.sap.com/webas/710/ws/configuration-descriptor}InterfaceData
 */
public  class InterfaceData extends com.sap.engine.services.webservices.espbase.configuration.Behaviour implements java.io.Serializable,java.lang.Cloneable {

  // Attribute field for attribute {}namespace
  private java.lang.String _a_Namespace;
  /**
   * Set method for attribute {}namespace
   */
  public void setNamespace(java.lang.String _Namespace) {
    this._a_Namespace = _Namespace;
  }
  /**
   * Get method for attribute {}namespace
   */
  public java.lang.String getNamespace() {
    return _a_Namespace;
  }

  // Attribute field for attribute {}name
  private java.lang.String _a_Name;
  /**
   * Set method for attribute {}name
   */
  public void setName(java.lang.String _Name) {
    this._a_Name = _Name;
  }
  /**
   * Get method for attribute {}name
   */
  public java.lang.String getName() {
    return _a_Name;
  }

  // Element field for element {}Operation
  private java.util.ArrayList _f_Operation = new java.util.ArrayList();
  /**
   * Set method for element {}Operation
   */
  public void setOperation(com.sap.engine.services.webservices.espbase.configuration.OperationData[] _Operation) {
    this._f_Operation.clear();
    if (_Operation != null) {
      for (int i=0; i<_Operation.length; i++) {
        if (_Operation[i] != null)
          this._f_Operation.add(_Operation[i]);
      }
    }
  }
  /**
   * Get method for element {}Operation
   */
  public com.sap.engine.services.webservices.espbase.configuration.OperationData[] getOperation() {
    com.sap.engine.services.webservices.espbase.configuration.OperationData[] result = new com.sap.engine.services.webservices.espbase.configuration.OperationData[_f_Operation.size()];
    _f_Operation.toArray(result);
    return result;
  }

  // Element field for element {}UDDIEntity
  private java.util.ArrayList _f_UDDIEntity = new java.util.ArrayList();
  /**
   * Set method for element {}UDDIEntity
   */
  public void setUDDIEntity(com.sap.engine.services.webservices.espbase.configuration.UDDIEntity[] _UDDIEntity) {
    this._f_UDDIEntity.clear();
    if (_UDDIEntity != null) {
      for (int i=0; i<_UDDIEntity.length; i++) {
        if (_UDDIEntity[i] != null)
          this._f_UDDIEntity.add(_UDDIEntity[i]);
      }
    }
  }
  /**
   * Get method for element {}UDDIEntity
   */
  public com.sap.engine.services.webservices.espbase.configuration.UDDIEntity[] getUDDIEntity() {
    com.sap.engine.services.webservices.espbase.configuration.UDDIEntity[] result = new com.sap.engine.services.webservices.espbase.configuration.UDDIEntity[_f_UDDIEntity.size()];
    _f_UDDIEntity.toArray(result);
    return result;
  }

  // Element field for element {}Description
  private java.util.ArrayList _f_Description = new java.util.ArrayList();
  /**
   * Set method for element {}Description
   */
  public void setDescription(com.sap.engine.services.webservices.espbase.configuration.Description[] _Description) {
    this._f_Description.clear();
    if (_Description != null) {
      for (int i=0; i<_Description.length; i++) {
        if (_Description[i] != null)
          this._f_Description.add(_Description[i]);
      }
    }
  }
  /**
   * Get method for element {}Description
   */
  public com.sap.engine.services.webservices.espbase.configuration.Description[] getDescription() {
    com.sap.engine.services.webservices.espbase.configuration.Description[] result = new com.sap.engine.services.webservices.espbase.configuration.Description[_f_Description.size()];
    _f_Description.toArray(result);
    return result;
  }

  // Element field for element {}ConfigValue
  private java.util.ArrayList _f_ConfigValue = new java.util.ArrayList();
  /**
   * Set method for element {}ConfigValue
   */
  public void setConfigValue(com.sap.engine.services.webservices.espbase.configuration.ConfigValueType[] _ConfigValue) {
    this._f_ConfigValue.clear();
    if (_ConfigValue != null) {
      for (int i=0; i<_ConfigValue.length; i++) {
        if (_ConfigValue[i] != null)
          this._f_ConfigValue.add(_ConfigValue[i]);
      }
    }
  }
  /**
   * Get method for element {}ConfigValue
   */
  public com.sap.engine.services.webservices.espbase.configuration.ConfigValueType[] getConfigValue() {
    com.sap.engine.services.webservices.espbase.configuration.ConfigValueType[] result = new com.sap.engine.services.webservices.espbase.configuration.ConfigValueType[_f_ConfigValue.size()];
    _f_ConfigValue.toArray(result);
    return result;
  }
  
  /**
   * @return OperationData with name equal to <code>opName</code>, or null if such operation is not found.
   */
  public OperationData getOperationData(String opName) {
    OperationData opD;
    for (int i = 0; i < this._f_Operation.size(); i++) {
      opD = (OperationData) _f_Operation.get(i);
      if (opD.getName().equals(opName)) {
        return opD;
      }
    }
    return null;
  }
  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (super.equals(object) == false) return false;
    if (object == null) return false;
    if (!(object instanceof InterfaceData)) return false;
    InterfaceData typed = (InterfaceData) object;
    if (this._a_Namespace != null) {
      if (typed._a_Namespace == null) return false;
      if (!this._a_Namespace.equals(typed._a_Namespace)) return false;
    } else {
      if (typed._a_Namespace != null) return false;
    }
    if (this._a_Name != null) {
      if (typed._a_Name == null) return false;
      if (!this._a_Name.equals(typed._a_Name)) return false;
    } else {
      if (typed._a_Name != null) return false;
    }
    com.sap.engine.services.webservices.espbase.configuration.OperationData[] _f_Operation1 = this.getOperation();
    com.sap.engine.services.webservices.espbase.configuration.OperationData[] _f_Operation2 = typed.getOperation();
    if (_f_Operation1 != null) {
      if (_f_Operation2 == null) return false;
      if (_f_Operation1.length != _f_Operation2.length) return false;
      for (int i1 = 0; i1 < _f_Operation1.length ; i1++) {
        if (_f_Operation1[i1] != null) {
          if (_f_Operation2[i1] == null) return false;
          if (!_f_Operation1[i1].equals(_f_Operation2[i1])) return false;
        } else {
          if (_f_Operation2[i1] != null) return false;
        }
      }
    } else {
      if (_f_Operation2 != null) return false;
    }
    com.sap.engine.services.webservices.espbase.configuration.UDDIEntity[] _f_UDDIEntity1 = this.getUDDIEntity();
    com.sap.engine.services.webservices.espbase.configuration.UDDIEntity[] _f_UDDIEntity2 = typed.getUDDIEntity();
    if (_f_UDDIEntity1 != null) {
      if (_f_UDDIEntity2 == null) return false;
      if (_f_UDDIEntity1.length != _f_UDDIEntity2.length) return false;
      for (int i1 = 0; i1 < _f_UDDIEntity1.length ; i1++) {
        if (_f_UDDIEntity1[i1] != null) {
          if (_f_UDDIEntity2[i1] == null) return false;
          if (!_f_UDDIEntity1[i1].equals(_f_UDDIEntity2[i1])) return false;
        } else {
          if (_f_UDDIEntity2[i1] != null) return false;
        }
      }
    } else {
      if (_f_UDDIEntity2 != null) return false;
    }
    com.sap.engine.services.webservices.espbase.configuration.Description[] _f_Description1 = this.getDescription();
    com.sap.engine.services.webservices.espbase.configuration.Description[] _f_Description2 = typed.getDescription();
    if (_f_Description1 != null) {
      if (_f_Description2 == null) return false;
      if (_f_Description1.length != _f_Description2.length) return false;
      for (int i1 = 0; i1 < _f_Description1.length ; i1++) {
        if (_f_Description1[i1] != null) {
          if (_f_Description2[i1] == null) return false;
          if (!_f_Description1[i1].equals(_f_Description2[i1])) return false;
        } else {
          if (_f_Description2[i1] != null) return false;
        }
      }
    } else {
      if (_f_Description2 != null) return false;
    }
    com.sap.engine.services.webservices.espbase.configuration.ConfigValueType[] _f_ConfigValue1 = this.getConfigValue();
    com.sap.engine.services.webservices.espbase.configuration.ConfigValueType[] _f_ConfigValue2 = typed.getConfigValue();
    if (_f_ConfigValue1 != null) {
      if (_f_ConfigValue2 == null) return false;
      if (_f_ConfigValue1.length != _f_ConfigValue2.length) return false;
      for (int i1 = 0; i1 < _f_ConfigValue1.length ; i1++) {
        if (_f_ConfigValue1[i1] != null) {
          if (_f_ConfigValue2[i1] == null) return false;
          if (!_f_ConfigValue1[i1].equals(_f_ConfigValue2[i1])) return false;
        } else {
          if (_f_ConfigValue2[i1] != null) return false;
        }
      }
    } else {
      if (_f_ConfigValue2 != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = super.hashCode();
    if (this._a_Namespace != null) {
      result+= this._a_Namespace.hashCode();
    }
    if (this._a_Name != null) {
      result+= this._a_Name.hashCode();
    }
    com.sap.engine.services.webservices.espbase.configuration.OperationData[] _f_Operation1 = this.getOperation();
    if (_f_Operation1 != null) {
      for (int i1 = 0; i1 < _f_Operation1.length ; i1++) {
        if (_f_Operation1[i1] != null) {
          result+= _f_Operation1[i1].hashCode();
        }
      }
    }
    com.sap.engine.services.webservices.espbase.configuration.UDDIEntity[] _f_UDDIEntity1 = this.getUDDIEntity();
    if (_f_UDDIEntity1 != null) {
      for (int i1 = 0; i1 < _f_UDDIEntity1.length ; i1++) {
        if (_f_UDDIEntity1[i1] != null) {
          result+= _f_UDDIEntity1[i1].hashCode();
        }
      }
    }
    com.sap.engine.services.webservices.espbase.configuration.Description[] _f_Description1 = this.getDescription();
    if (_f_Description1 != null) {
      for (int i1 = 0; i1 < _f_Description1.length ; i1++) {
        if (_f_Description1[i1] != null) {
          result+= _f_Description1[i1].hashCode();
        }
      }
    }
    com.sap.engine.services.webservices.espbase.configuration.ConfigValueType[] _f_ConfigValue1 = this.getConfigValue();
    if (_f_ConfigValue1 != null) {
      for (int i1 = 0; i1 < _f_ConfigValue1.length ; i1++) {
        if (_f_ConfigValue1[i1] != null) {
          result+= _f_ConfigValue1[i1].hashCode();
        }
      }
    }
    return result;
  }
  /**
   * Creates new InterfaceData object that reflects the internal fields of <code>this</code>, as well as nested operation datas and their internal fields.
   * Only the property lists are not copied.
   */
  public InterfaceData makeCopyWithoutProperties() {
    InterfaceData newI = new InterfaceData();
    newI.setName(this.getName());
    newI.setNamespace(this.getNamespace());
    //TODO remove this
    newI.getSinglePropertyList().setSelected(Boolean.TRUE); 
    OperationData thisOps[] = this.getOperation();
    OperationData newIOps[] = new OperationData[thisOps.length];
    for (int i = 0; i < thisOps.length; i++) {
      newIOps[i] = thisOps[i].makeCopyWithoutProperties();
    }
    newI.setOperation(newIOps);
    return newI;
  }
}
