/*
 * Generated by SAP SchemaToJava Generator NW05 on Tue Feb 22 14:02:04 EET 2005
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.services.webservices.espbase.configuration;

/**
 * Schema complexType Java representation.
 * Represents type {http://www.sap.com/webas/710/ws/configuration-descriptor}UDDIServer
 */
public  class UDDIServer implements java.io.Serializable,java.lang.Cloneable {

  // // Active choise field
  private int _c_validField = 0;
  private java.lang.String _f_SIDName;
  /**
   * Set method for element {}SIDName
   */
  public void setSIDName(java.lang.String _SIDName) {
    if (this._c_validField != 0 && this._c_validField != 1) {
      this.unsetContent();
    }
    this._f_SIDName = _SIDName;
    this._c_validField = 1;
  }
  /**
   * Get method for element {}SIDName
   */
  public java.lang.String getSIDName() {
    if (this._c_validField != 1) {
      return null;
    }
    return this._f_SIDName;
  }
  /**
   * Check method for element {}SIDName
   */
  public boolean isSetSIDName() {
    return (this._c_validField ==1);
  }
  private java.lang.String _f_InquiryURL;
  /**
   * Set method for element {}InquiryURL
   */
  public void setInquiryURL(java.lang.String _InquiryURL) {
    if (this._c_validField != 0 && this._c_validField != 2) {
      this.unsetContent();
    }
    this._f_InquiryURL = _InquiryURL;
    this._c_validField = 2;
  }
  /**
   * Get method for element {}InquiryURL
   */
  public java.lang.String getInquiryURL() {
    if (this._c_validField != 2) {
      return null;
    }
    return this._f_InquiryURL;
  }
  /**
   * Check method for element {}InquiryURL
   */
  public boolean isSetInquiryURL() {
    return (this._c_validField ==2);
  }
  /**
   * Common get method for choice type.
   */
  public java.lang.String getContent() {
    switch (this._c_validField) {
      case 1: return this._f_SIDName;
      case 2: return this._f_InquiryURL;
    }
    return null;
  }
  /**
   * Returns true if this choice has content set.
   */
  public boolean isSetContent() {
    return (this._c_validField == 0);
  }
  /**
   * Clears choice content.
   */
  public void unsetContent() {
    switch (this._c_validField) {
      case  1: {
        this._f_SIDName = null;
        break;
      }
      case  2: {
        this._f_InquiryURL = null;
        break;
      }
    }
    this._c_validField = 0;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof UDDIServer)) return false;
    UDDIServer typed = (UDDIServer) object;
    if (this._c_validField != typed._c_validField) return false;
    switch (this._c_validField) {
      case 1: {
        if (this._f_SIDName != null) {
          if (typed._f_SIDName == null) return false;
          if (!this._f_SIDName.equals(typed._f_SIDName)) return false;
        } else {
          if (typed._f_SIDName != null) return false;
        }
        break;
      }
      case 2: {
        if (this._f_InquiryURL != null) {
          if (typed._f_InquiryURL == null) return false;
          if (!this._f_InquiryURL.equals(typed._f_InquiryURL)) return false;
        } else {
          if (typed._f_InquiryURL != null) return false;
        }
        break;
      }
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    switch (this._c_validField) {
      case 1: {
        if (this._f_SIDName != null) {
          result+= this._f_SIDName.hashCode();
        }
        result = result * this._c_validField;
        break;
      }
      case 2: {
        if (this._f_InquiryURL != null) {
          result+= this._f_InquiryURL.hashCode();
        }
        result = result * this._c_validField;
        break;
      }
    }
    return result;
  }
}
