
package com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types;


/**
 * Schema complex type representation (generated by SAP Schema to Java generator).
 * Represents schema complex type {urn:uddi-org:api_v2}addressLine
 */

public  class AddressLine extends com.sap.engine.services.webservices.jaxrpc.encoding.GeneratedComplexType {


  public java.lang.String _d_originalUri() {
    return "urn:uddi-org:api_v2";
  }

  public java.lang.String _d_originalLocalName() {
    return "addressLine";
  }

  private static com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[] ATTRIBUTEINFO;

  private synchronized static void initAttribs() {
    // Creating attribute fields
    if (ATTRIBUTEINFO != null) return;
    ATTRIBUTEINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[2];
    ATTRIBUTEINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo();
    ATTRIBUTEINFO[1] = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo();
    // Attribute 0
    ATTRIBUTEINFO[0].fieldLocalName = "keyName";
    ATTRIBUTEINFO[0].fieldUri = "";
    ATTRIBUTEINFO[0].fieldJavaName = "KeyName";
    ATTRIBUTEINFO[0].typeName = "string";
    ATTRIBUTEINFO[0].typeUri = "http://www.w3.org/2001/XMLSchema";
    ATTRIBUTEINFO[0].typeJavaName = "java.lang.String";
    ATTRIBUTEINFO[0].defaultValue = null;
    ATTRIBUTEINFO[0].required = false;
    ATTRIBUTEINFO[0].setterMethod = "setKeyName";
    ATTRIBUTEINFO[0].getterMethod = "getKeyName";
    ATTRIBUTEINFO[0].checkMethod = "hasKeyName";
    // Attribute 1
    ATTRIBUTEINFO[1].fieldLocalName = "keyValue";
    ATTRIBUTEINFO[1].fieldUri = "";
    ATTRIBUTEINFO[1].fieldJavaName = "KeyValue";
    ATTRIBUTEINFO[1].typeName = "string";
    ATTRIBUTEINFO[1].typeUri = "http://www.w3.org/2001/XMLSchema";
    ATTRIBUTEINFO[1].typeJavaName = "java.lang.String";
    ATTRIBUTEINFO[1].defaultValue = null;
    ATTRIBUTEINFO[1].required = false;
    ATTRIBUTEINFO[1].setterMethod = "setKeyValue";
    ATTRIBUTEINFO[1].getterMethod = "getKeyValue";
    ATTRIBUTEINFO[1].checkMethod = "hasKeyValue";
  }

  // Field information
  private static com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] FIELDINFO;

  private synchronized static void initFields() {
    // Creating fields
    if (FIELDINFO != null) return;
    FIELDINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[1];
    FIELDINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    // Field 0
    FIELDINFO[0].defaultValue = null;
    FIELDINFO[0].fieldJavaName = "SimpleContent";
    FIELDINFO[0].fieldLocalName = "";
    FIELDINFO[0].fieldModel = 0;
    FIELDINFO[0].fieldUri = "urn:uddi-org:api_v2";
    FIELDINFO[0].isSoapArray = false;
    FIELDINFO[0].maxOccurs = 1;
    FIELDINFO[0].minOccurs = 1;
    FIELDINFO[0].nillable = false;
    FIELDINFO[0].soapArrayDimensions = 0;
    FIELDINFO[0].soapArrayItemTypeJavaName = null;
    FIELDINFO[0].soapArrayItemTypeLocalName = null;
    FIELDINFO[0].soapArrayItemTypeUri = null;
    FIELDINFO[0].typeJavaName = "java.lang.String";
    FIELDINFO[0].typeLocalName = "string";
    FIELDINFO[0].typeUri = "http://www.w3.org/2001/XMLSchema";
    FIELDINFO[0].getterMethod = "getSimpleContent";
    FIELDINFO[0].setterMethod = "setSimpleContent";
    FIELDINFO[0].checkMethod = "hasSimpleContent";
  }


  // Returns model Group Type
  public int _getModelType() {
    return 0;
  }

  // Attribute field
  private java.lang.String _a_KeyName;
  private boolean _a_hasKeyName;
  // set method
  public void setKeyName(java.lang.String _KeyName) {
    this._a_KeyName = _KeyName;
    this._a_hasKeyName = true;
  }
  // clear method
  public void clearKeyName(java.lang.String _KeyName) {
    this._a_hasKeyName = false;
  }
  // get method
  public java.lang.String getKeyName() {
    return _a_KeyName;
  }
  // has method
  public boolean hasKeyName() {
    return _a_hasKeyName;
  }

  // Attribute field
  private java.lang.String _a_KeyValue;
  private boolean _a_hasKeyValue;
  // set method
  public void setKeyValue(java.lang.String _KeyValue) {
    this._a_KeyValue = _KeyValue;
    this._a_hasKeyValue = true;
  }
  // clear method
  public void clearKeyValue(java.lang.String _KeyValue) {
    this._a_hasKeyValue = false;
  }
  // get method
  public java.lang.String getKeyValue() {
    return _a_KeyValue;
  }
  // has method
  public boolean hasKeyValue() {
    return _a_hasKeyValue;
  }

  // Element field
  private java.lang.String _f_SimpleContent;

  public void setSimpleContent(java.lang.String _SimpleContent) {
    this._f_SimpleContent = _SimpleContent;
  }

  public java.lang.String getSimpleContent() {
    return this._f_SimpleContent;
  }

  private static boolean init = false;
  public synchronized com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] _getFields() {
    if (init == false) {
      com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] parent = super._getFields();
      FIELDINFO =  _insertFieldInfo(parent,FIELDINFO);
      init = true;
    }
    return FIELDINFO;
  }

  public int _getNumberOfFields() {
    return (FIELDINFO.length+super._getNumberOfFields());
  }

  public com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[] _getAttributes() {
    return ATTRIBUTEINFO;
  }

  public int _getNumberOfAttributes() {
    return ATTRIBUTEINFO.length;
  }

  static {
    initFields();
    initAttribs();
  }
}
