
package com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types;


/**
 * Schema complex type representation (generated by SAP Schema to Java generator).
 * Represents schema complex type {urn:uddi-org:api_v2}relatedBusinessInfo
 */

public  class RelatedBusinessInfo extends com.sap.engine.services.webservices.jaxrpc.encoding.GeneratedComplexType {


  public java.lang.String _d_originalUri() {
    return "urn:uddi-org:api_v2";
  }

  public java.lang.String _d_originalLocalName() {
    return "relatedBusinessInfo";
  }

  private static com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[] ATTRIBUTEINFO;

  private synchronized static void initAttribs() {
    // Creating attribute fields
    if (ATTRIBUTEINFO != null) return;
    ATTRIBUTEINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[0];
  }

  // Field information
  private static com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] FIELDINFO;

  private synchronized static void initFields() {
    // Creating fields
    if (FIELDINFO != null) return;
    FIELDINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[4];
    FIELDINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    FIELDINFO[1] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    FIELDINFO[2] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    FIELDINFO[3] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    // Field 0
    FIELDINFO[0].defaultValue = null;
    FIELDINFO[0].fieldJavaName = "BusinessKey";
    FIELDINFO[0].fieldLocalName = "businessKey";
    FIELDINFO[0].fieldModel = 1;
    FIELDINFO[0].fieldUri = "urn:uddi-org:api_v2";
    FIELDINFO[0].isSoapArray = false;
    FIELDINFO[0].maxOccurs = 1;
    FIELDINFO[0].minOccurs = 1;
    FIELDINFO[0].nillable = false;
    FIELDINFO[0].soapArrayDimensions = 0;
    FIELDINFO[0].soapArrayItemTypeJavaName = null;
    FIELDINFO[0].soapArrayItemTypeLocalName = null;
    FIELDINFO[0].soapArrayItemTypeUri = null;
    FIELDINFO[0].typeJavaName = "java.lang.String";
    FIELDINFO[0].typeLocalName = "businessKey";
    FIELDINFO[0].typeUri = "urn:uddi-org:api_v2";
    FIELDINFO[0].getterMethod = "getBusinessKey";
    FIELDINFO[0].setterMethod = "setBusinessKey";
    FIELDINFO[0].checkMethod = "hasBusinessKey";
    // Field 1
    FIELDINFO[1].defaultValue = null;
    FIELDINFO[1].fieldJavaName = "Name";
    FIELDINFO[1].fieldLocalName = "name";
    FIELDINFO[1].fieldModel = 1;
    FIELDINFO[1].fieldUri = "urn:uddi-org:api_v2";
    FIELDINFO[1].isSoapArray = false;
    FIELDINFO[1].maxOccurs = 2147483647;
    FIELDINFO[1].minOccurs = 1;
    FIELDINFO[1].nillable = false;
    FIELDINFO[1].soapArrayDimensions = 0;
    FIELDINFO[1].soapArrayItemTypeJavaName = null;
    FIELDINFO[1].soapArrayItemTypeLocalName = null;
    FIELDINFO[1].soapArrayItemTypeUri = null;
    FIELDINFO[1].typeJavaName = "com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.Name";
    FIELDINFO[1].typeLocalName = "name";
    FIELDINFO[1].typeUri = "urn:uddi-org:api_v2";
    FIELDINFO[1].getterMethod = "getName";
    FIELDINFO[1].setterMethod = "setName";
    FIELDINFO[1].checkMethod = "hasName";
    // Field 2
    FIELDINFO[2].defaultValue = null;
    FIELDINFO[2].fieldJavaName = "Description";
    FIELDINFO[2].fieldLocalName = "description";
    FIELDINFO[2].fieldModel = 1;
    FIELDINFO[2].fieldUri = "urn:uddi-org:api_v2";
    FIELDINFO[2].isSoapArray = false;
    FIELDINFO[2].maxOccurs = 2147483647;
    FIELDINFO[2].minOccurs = 0;
    FIELDINFO[2].nillable = false;
    FIELDINFO[2].soapArrayDimensions = 0;
    FIELDINFO[2].soapArrayItemTypeJavaName = null;
    FIELDINFO[2].soapArrayItemTypeLocalName = null;
    FIELDINFO[2].soapArrayItemTypeUri = null;
    FIELDINFO[2].typeJavaName = "com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.Description";
    FIELDINFO[2].typeLocalName = "description";
    FIELDINFO[2].typeUri = "urn:uddi-org:api_v2";
    FIELDINFO[2].getterMethod = "getDescription";
    FIELDINFO[2].setterMethod = "setDescription";
    FIELDINFO[2].checkMethod = "hasDescription";
    // Field 3
    FIELDINFO[3].defaultValue = null;
    FIELDINFO[3].fieldJavaName = "SharedRelationships";
    FIELDINFO[3].fieldLocalName = "sharedRelationships";
    FIELDINFO[3].fieldModel = 1;
    FIELDINFO[3].fieldUri = "urn:uddi-org:api_v2";
    FIELDINFO[3].isSoapArray = false;
    FIELDINFO[3].maxOccurs = 2;
    FIELDINFO[3].minOccurs = 1;
    FIELDINFO[3].nillable = false;
    FIELDINFO[3].soapArrayDimensions = 0;
    FIELDINFO[3].soapArrayItemTypeJavaName = null;
    FIELDINFO[3].soapArrayItemTypeLocalName = null;
    FIELDINFO[3].soapArrayItemTypeUri = null;
    FIELDINFO[3].typeJavaName = "com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.SharedRelationships";
    FIELDINFO[3].typeLocalName = "sharedRelationships";
    FIELDINFO[3].typeUri = "urn:uddi-org:api_v2";
    FIELDINFO[3].getterMethod = "getSharedRelationships";
    FIELDINFO[3].setterMethod = "setSharedRelationships";
    FIELDINFO[3].checkMethod = "hasSharedRelationships";
  }


  // Returns model Group Type
  public int _getModelType() {
    return 3;
  }

  // Element field
  private java.lang.String _f_BusinessKey;

  public void setBusinessKey(java.lang.String _BusinessKey) {
    this._f_BusinessKey = _BusinessKey;
  }

  public java.lang.String getBusinessKey() {
    return this._f_BusinessKey;
  }

  // Element field
  private com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.Name[] _f_Name = new com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.Name[0];
  public void setName(com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.Name[] _Name) {
    this._f_Name = _Name;
  }
  public com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.Name[] getName() {
    return _f_Name;
  }

  // Element field
  private com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.Description[] _f_Description = new com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.Description[0];
  public void setDescription(com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.Description[] _Description) {
    this._f_Description = _Description;
  }
  public com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.Description[] getDescription() {
    return _f_Description;
  }

  // Element field
  private com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.SharedRelationships[] _f_SharedRelationships = new com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.SharedRelationships[0];
  public void setSharedRelationships(com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.SharedRelationships[] _SharedRelationships) {
    this._f_SharedRelationships = _SharedRelationships;
  }
  public com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.SharedRelationships[] getSharedRelationships() {
    return _f_SharedRelationships;
  }

  private static boolean init = false;
  public synchronized com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] _getFields() {
    if (init == false) {
      com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] parent = super._getFields();
      FIELDINFO =  _insertFieldInfo(parent,FIELDINFO);
      init = true;
    }
    return FIELDINFO;
  }

  public int _getNumberOfFields() {
    return (FIELDINFO.length+super._getNumberOfFields());
  }

  public com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[] _getAttributes() {
    return ATTRIBUTEINFO;
  }

  public int _getNumberOfAttributes() {
    return ATTRIBUTEINFO.length;
  }

  static {
    initFields();
    initAttribs();
  }
}
