
package com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types;


/**
 * Schema complex type representation (generated by SAP Schema to Java generator).
 * Represents schema complex type {urn:uddi-org:api_v2}sharedRelationships
 */

public  class SharedRelationships extends com.sap.engine.services.webservices.jaxrpc.encoding.GeneratedComplexType {


  public java.lang.String _d_originalUri() {
    return "urn:uddi-org:api_v2";
  }

  public java.lang.String _d_originalLocalName() {
    return "sharedRelationships";
  }

  private static com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[] ATTRIBUTEINFO;

  private synchronized static void initAttribs() {
    // Creating attribute fields
    if (ATTRIBUTEINFO != null) return;
    ATTRIBUTEINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[1];
    ATTRIBUTEINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo();
    // Attribute 0
    ATTRIBUTEINFO[0].fieldLocalName = "direction";
    ATTRIBUTEINFO[0].fieldUri = "";
    ATTRIBUTEINFO[0].fieldJavaName = "Direction";
    ATTRIBUTEINFO[0].typeName = "direction";
    ATTRIBUTEINFO[0].typeUri = "urn:uddi-org:api_v2";
    ATTRIBUTEINFO[0].typeJavaName = "java.lang.String";
    ATTRIBUTEINFO[0].defaultValue = null;
    ATTRIBUTEINFO[0].required = true;
    ATTRIBUTEINFO[0].setterMethod = "setDirection";
    ATTRIBUTEINFO[0].getterMethod = "getDirection";
    ATTRIBUTEINFO[0].checkMethod = "hasDirection";
  }

  // Field information
  private static com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] FIELDINFO;

  private synchronized static void initFields() {
    // Creating fields
    if (FIELDINFO != null) return;
    FIELDINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[1];
    FIELDINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    // Field 0
    FIELDINFO[0].defaultValue = null;
    FIELDINFO[0].fieldJavaName = "KeyedReference";
    FIELDINFO[0].fieldLocalName = "keyedReference";
    FIELDINFO[0].fieldModel = 1;
    FIELDINFO[0].fieldUri = "urn:uddi-org:api_v2";
    FIELDINFO[0].isSoapArray = false;
    FIELDINFO[0].maxOccurs = 2147483647;
    FIELDINFO[0].minOccurs = 1;
    FIELDINFO[0].nillable = false;
    FIELDINFO[0].soapArrayDimensions = 0;
    FIELDINFO[0].soapArrayItemTypeJavaName = null;
    FIELDINFO[0].soapArrayItemTypeLocalName = null;
    FIELDINFO[0].soapArrayItemTypeUri = null;
    FIELDINFO[0].typeJavaName = "com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.KeyedReference";
    FIELDINFO[0].typeLocalName = "keyedReference";
    FIELDINFO[0].typeUri = "urn:uddi-org:api_v2";
    FIELDINFO[0].getterMethod = "getKeyedReference";
    FIELDINFO[0].setterMethod = "setKeyedReference";
    FIELDINFO[0].checkMethod = "hasKeyedReference";
  }


  // Returns model Group Type
  public int _getModelType() {
    return 3;
  }

  // Attribute field
  private java.lang.String _a_Direction;
  private boolean _a_hasDirection;
  // set method
  public void setDirection(java.lang.String _Direction) {
    this._a_Direction = _Direction;
    this._a_hasDirection = true;
  }
  // clear method
  public void clearDirection(java.lang.String _Direction) {
    this._a_hasDirection = false;
  }
  // get method
  public java.lang.String getDirection() {
    return _a_Direction;
  }
  // has method
  public boolean hasDirection() {
    return _a_hasDirection;
  }

  // Element field
  private com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.KeyedReference[] _f_KeyedReference = new com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.KeyedReference[0];
  public void setKeyedReference(com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.KeyedReference[] _KeyedReference) {
    this._f_KeyedReference = _KeyedReference;
  }
  public com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.KeyedReference[] getKeyedReference() {
    return _f_KeyedReference;
  }

  private static boolean init = false;
  public synchronized com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] _getFields() {
    if (init == false) {
      com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] parent = super._getFields();
      FIELDINFO =  _insertFieldInfo(parent,FIELDINFO);
      init = true;
    }
    return FIELDINFO;
  }

  public int _getNumberOfFields() {
    return (FIELDINFO.length+super._getNumberOfFields());
  }

  public com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[] _getAttributes() {
    return ATTRIBUTEINFO;
  }

  public int _getNumberOfAttributes() {
    return ATTRIBUTEINFO.length;
  }

  static {
    initFields();
    initAttribs();
  }
}
