
package com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types;


/**
 * Schema complex type representation (generated by SAP Schema to Java generator).
 * Represents schema complex type {urn:uddi-org:api_v2}validate_values
 */

public  class ValidateValues extends com.sap.engine.services.webservices.jaxrpc.encoding.GeneratedComplexType {


  public java.lang.String _d_originalUri() {
    return "urn:uddi-org:api_v2";
  }

  public java.lang.String _d_originalLocalName() {
    return "validate_values";
  }

  private static com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[] ATTRIBUTEINFO;

  private synchronized static void initAttribs() {
    // Creating attribute fields
    if (ATTRIBUTEINFO != null) return;
    ATTRIBUTEINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[1];
    ATTRIBUTEINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo();
    // Attribute 0
    ATTRIBUTEINFO[0].fieldLocalName = "generic";
    ATTRIBUTEINFO[0].fieldUri = "";
    ATTRIBUTEINFO[0].fieldJavaName = "Generic";
    ATTRIBUTEINFO[0].typeName = "string";
    ATTRIBUTEINFO[0].typeUri = "http://www.w3.org/2001/XMLSchema";
    ATTRIBUTEINFO[0].typeJavaName = "java.lang.String";
    ATTRIBUTEINFO[0].defaultValue = null;
    ATTRIBUTEINFO[0].required = true;
    ATTRIBUTEINFO[0].setterMethod = "setGeneric";
    ATTRIBUTEINFO[0].getterMethod = "getGeneric";
    ATTRIBUTEINFO[0].checkMethod = "hasGeneric";
  }

  // Field information
  private static com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] FIELDINFO;

  private synchronized static void initFields() {
    // Creating fields
    if (FIELDINFO != null) return;
    FIELDINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[3];
    FIELDINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    FIELDINFO[1] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    FIELDINFO[2] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    // Field 0
    FIELDINFO[0].defaultValue = null;
    FIELDINFO[0].fieldJavaName = "BusinessEntity";
    FIELDINFO[0].fieldLocalName = "businessEntity";
    FIELDINFO[0].fieldModel = 1;
    FIELDINFO[0].fieldUri = "urn:uddi-org:api_v2";
    FIELDINFO[0].isSoapArray = false;
    FIELDINFO[0].maxOccurs = 2147483647;
    FIELDINFO[0].minOccurs = 0;
    FIELDINFO[0].nillable = false;
    FIELDINFO[0].soapArrayDimensions = 0;
    FIELDINFO[0].soapArrayItemTypeJavaName = null;
    FIELDINFO[0].soapArrayItemTypeLocalName = null;
    FIELDINFO[0].soapArrayItemTypeUri = null;
    FIELDINFO[0].typeJavaName = "com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.BusinessEntity";
    FIELDINFO[0].typeLocalName = "businessEntity";
    FIELDINFO[0].typeUri = "urn:uddi-org:api_v2";
    FIELDINFO[0].getterMethod = "getBusinessEntity";
    FIELDINFO[0].setterMethod = "setBusinessEntity";
    FIELDINFO[0].checkMethod = "hasBusinessEntity";
    // Field 1
    FIELDINFO[1].defaultValue = null;
    FIELDINFO[1].fieldJavaName = "BusinessService";
    FIELDINFO[1].fieldLocalName = "businessService";
    FIELDINFO[1].fieldModel = 1;
    FIELDINFO[1].fieldUri = "urn:uddi-org:api_v2";
    FIELDINFO[1].isSoapArray = false;
    FIELDINFO[1].maxOccurs = 2147483647;
    FIELDINFO[1].minOccurs = 0;
    FIELDINFO[1].nillable = false;
    FIELDINFO[1].soapArrayDimensions = 0;
    FIELDINFO[1].soapArrayItemTypeJavaName = null;
    FIELDINFO[1].soapArrayItemTypeLocalName = null;
    FIELDINFO[1].soapArrayItemTypeUri = null;
    FIELDINFO[1].typeJavaName = "com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.BusinessService";
    FIELDINFO[1].typeLocalName = "businessService";
    FIELDINFO[1].typeUri = "urn:uddi-org:api_v2";
    FIELDINFO[1].getterMethod = "getBusinessService";
    FIELDINFO[1].setterMethod = "setBusinessService";
    FIELDINFO[1].checkMethod = "hasBusinessService";
    // Field 2
    FIELDINFO[2].defaultValue = null;
    FIELDINFO[2].fieldJavaName = "TModel";
    FIELDINFO[2].fieldLocalName = "tModel";
    FIELDINFO[2].fieldModel = 1;
    FIELDINFO[2].fieldUri = "urn:uddi-org:api_v2";
    FIELDINFO[2].isSoapArray = false;
    FIELDINFO[2].maxOccurs = 2147483647;
    FIELDINFO[2].minOccurs = 0;
    FIELDINFO[2].nillable = false;
    FIELDINFO[2].soapArrayDimensions = 0;
    FIELDINFO[2].soapArrayItemTypeJavaName = null;
    FIELDINFO[2].soapArrayItemTypeLocalName = null;
    FIELDINFO[2].soapArrayItemTypeUri = null;
    FIELDINFO[2].typeJavaName = "com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.TModel";
    FIELDINFO[2].typeLocalName = "tModel";
    FIELDINFO[2].typeUri = "urn:uddi-org:api_v2";
    FIELDINFO[2].getterMethod = "getTModel";
    FIELDINFO[2].setterMethod = "setTModel";
    FIELDINFO[2].checkMethod = "hasTModel";
  }


  // Returns model Group Type
  public int _getModelType() {
    return 2;
  }

  // Attribute field
  private java.lang.String _a_Generic;
  private boolean _a_hasGeneric;
  // set method
  public void setGeneric(java.lang.String _Generic) {
    this._a_Generic = _Generic;
    this._a_hasGeneric = true;
  }
  // clear method
  public void clearGeneric(java.lang.String _Generic) {
    this._a_hasGeneric = false;
  }
  // get method
  public java.lang.String getGeneric() {
    return _a_Generic;
  }
  // has method
  public boolean hasGeneric() {
    return _a_hasGeneric;
  }

  // // Active choise field
  private int _c_validField = 0;

  // Choice field
  private com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.BusinessEntity[] _c_BusinessEntity = new com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.BusinessEntity[0];

  public com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.BusinessEntity[] getBusinessEntity() throws Exception {
    if (_c_validField != 1) {
      throw new Exception("Field 'businessEntity' has not been set");
    } else {
      return _c_BusinessEntity;
    }
  }

  public boolean hasBusinessEntity() {
    return (_c_validField ==1);
  }

  public void setBusinessEntity(com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.BusinessEntity[] _BusinessEntity) {
    this._c_validField = 1;
    this._c_BusinessEntity = _BusinessEntity;
  }

  // Choice field
  private com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.BusinessService[] _c_BusinessService = new com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.BusinessService[0];

  public com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.BusinessService[] getBusinessService() throws Exception {
    if (_c_validField != 2) {
      throw new Exception(" Field 'businessService' has not been set");
    } else {
      return _c_BusinessService;
    }
  }

  public boolean hasBusinessService() {
    return (_c_validField ==2);
  }

  public void setBusinessService(com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.BusinessService[] _BusinessService) {
    this._c_validField = 2;
    this._c_BusinessService = _BusinessService;
  }

  // Choice field
  private com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.TModel[] _c_TModel = new com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.TModel[0];

  public com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.TModel[] getTModel() throws Exception {
    if (_c_validField != 3) {
      throw new Exception("Field 'tModel' has not been set");
    } else {
      return _c_TModel;
    }
  }

  public boolean hasTModel() {
    return (_c_validField ==3);
  }

  public void setTModel(com.sap.engine.services.webservices.jaxr.impl.uddi_v2.types.TModel[] _TModel) {
    this._c_validField = 3;
    this._c_TModel = _TModel;
  }

  private static boolean init = false;
  public synchronized com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] _getFields() {
    if (init == false) {
      com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] parent = super._getFields();
      FIELDINFO =  _insertFieldInfo(parent,FIELDINFO);
      init = true;
    }
    return FIELDINFO;
  }

  public int _getNumberOfFields() {
    return (FIELDINFO.length+super._getNumberOfFields());
  }

  public com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[] _getAttributes() {
    return ATTRIBUTEINFO;
  }

  public int _getNumberOfAttributes() {
    return ATTRIBUTEINFO.length;
  }

  static {
    initFields();
    initAttribs();
  }
}
