/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon May 29 10:14:50 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.sapcontrol.client.types;

/**
 * Schema complexType Java representation.
 * Represents type of namespace {urn:SAPControl} anonymous with xpath [/definitions/types/schema/element[50]/complexType]
 */
public  class ABAPReadRawSyslogResponse implements java.io.Serializable {

  // Element field for element {}log
  private com.sap.sapcontrol.client.types.ArrayOfRawSyslogEntry _f_Log;
  /**
   * Set method for element {}log
   */
  public void setLog(com.sap.sapcontrol.client.types.ArrayOfRawSyslogEntry _Log) {
    this._f_Log = _Log;
  }
  /**
   * Get method for element {}log
   */
  public com.sap.sapcontrol.client.types.ArrayOfRawSyslogEntry getLog() {
    return this._f_Log;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof ABAPReadRawSyslogResponse)) return false;
    ABAPReadRawSyslogResponse typed = (ABAPReadRawSyslogResponse) object;
    if (this._f_Log != null) {
      if (typed._f_Log == null) return false;
      if (!this._f_Log.equals(typed._f_Log)) return false;
    } else {
      if (typed._f_Log != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Log != null) {
      result+= this._f_Log.hashCode();
    }
    return result;
  }
}
