/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon May 29 10:14:50 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.sapcontrol.client.types;

/**
 * Schema complexType Java representation.
 * Represents type {urn:SAPControl}AccessPoint
 */
public  class AccessPoint implements java.io.Serializable {

  // Element field for element {}address
  private java.lang.String _f_Address;
  /**
   * Set method for element {}address
   */
  public void setAddress(java.lang.String _Address) {
    this._f_Address = _Address;
  }
  /**
   * Get method for element {}address
   */
  public java.lang.String getAddress() {
    return this._f_Address;
  }

  // Element field for element {}port
  private int _f_Port;
  /**
   * Set method for element {}port
   */
  public void setPort(int _Port) {
    this._f_Port = _Port;
  }
  /**
   * Get method for element {}port
   */
  public int getPort() {
    return this._f_Port;
  }

  // Element field for element {}protocol
  private java.lang.String _f_Protocol;
  /**
   * Set method for element {}protocol
   */
  public void setProtocol(java.lang.String _Protocol) {
    this._f_Protocol = _Protocol;
  }
  /**
   * Get method for element {}protocol
   */
  public java.lang.String getProtocol() {
    return this._f_Protocol;
  }

  // Element field for element {}processname
  private java.lang.String _f_Processname;
  /**
   * Set method for element {}processname
   */
  public void setProcessname(java.lang.String _Processname) {
    this._f_Processname = _Processname;
  }
  /**
   * Get method for element {}processname
   */
  public java.lang.String getProcessname() {
    return this._f_Processname;
  }

  // Element field for element {}active
  private java.lang.String _f_Active;
  /**
   * Set method for element {}active
   */
  public void setActive(java.lang.String _Active) {
    this._f_Active = _Active;
  }
  /**
   * Get method for element {}active
   */
  public java.lang.String getActive() {
    return this._f_Active;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof AccessPoint)) return false;
    AccessPoint typed = (AccessPoint) object;
    if (this._f_Address != null) {
      if (typed._f_Address == null) return false;
      if (!this._f_Address.equals(typed._f_Address)) return false;
    } else {
      if (typed._f_Address != null) return false;
    }
    if (this._f_Port != typed._f_Port) return false;
    if (this._f_Protocol != null) {
      if (typed._f_Protocol == null) return false;
      if (!this._f_Protocol.equals(typed._f_Protocol)) return false;
    } else {
      if (typed._f_Protocol != null) return false;
    }
    if (this._f_Processname != null) {
      if (typed._f_Processname == null) return false;
      if (!this._f_Processname.equals(typed._f_Processname)) return false;
    } else {
      if (typed._f_Processname != null) return false;
    }
    if (this._f_Active != null) {
      if (typed._f_Active == null) return false;
      if (!this._f_Active.equals(typed._f_Active)) return false;
    } else {
      if (typed._f_Active != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Address != null) {
      result+= this._f_Address.hashCode();
    }
    result+= (int) this._f_Port;
    if (this._f_Protocol != null) {
      result+= this._f_Protocol.hashCode();
    }
    if (this._f_Processname != null) {
      result+= this._f_Processname.hashCode();
    }
    if (this._f_Active != null) {
      result+= this._f_Active.hashCode();
    }
    return result;
  }
}
