/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon May 29 10:14:50 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.sapcontrol.client.types;

/**
 * Schema complexType Java representation.
 * Represents type {urn:SAPControl}Alert
 */
public  class Alert implements java.io.Serializable {

  // Element field for element {}Object
  private java.lang.String _f_Object;
  /**
   * Set method for element {}Object
   */
  public void setObject(java.lang.String _Object) {
    this._f_Object = _Object;
  }
  /**
   * Get method for element {}Object
   */
  public java.lang.String getObject() {
    return this._f_Object;
  }

  // Element field for element {}Attribute
  private java.lang.String _f_Attribute;
  /**
   * Set method for element {}Attribute
   */
  public void setAttribute(java.lang.String _Attribute) {
    this._f_Attribute = _Attribute;
  }
  /**
   * Get method for element {}Attribute
   */
  public java.lang.String getAttribute() {
    return this._f_Attribute;
  }

  // Element field for element {}Value
  private com.sap.sapcontrol.client.types.STATECOLOR _f_Value;
  /**
   * Set method for element {}Value
   */
  public void setValue(com.sap.sapcontrol.client.types.STATECOLOR _Value) {
    this._f_Value = _Value;
  }
  /**
   * Get method for element {}Value
   */
  public com.sap.sapcontrol.client.types.STATECOLOR getValue() {
    return this._f_Value;
  }

  // Element field for element {}Description
  private java.lang.String _f_Description;
  /**
   * Set method for element {}Description
   */
  public void setDescription(java.lang.String _Description) {
    this._f_Description = _Description;
  }
  /**
   * Get method for element {}Description
   */
  public java.lang.String getDescription() {
    return this._f_Description;
  }

  // Element field for element {}Time
  private java.lang.String _f_Time;
  /**
   * Set method for element {}Time
   */
  public void setTime(java.lang.String _Time) {
    this._f_Time = _Time;
  }
  /**
   * Get method for element {}Time
   */
  public java.lang.String getTime() {
    return this._f_Time;
  }

  // Element field for element {}Tid
  private java.lang.String _f_Tid;
  /**
   * Set method for element {}Tid
   */
  public void setTid(java.lang.String _Tid) {
    this._f_Tid = _Tid;
  }
  /**
   * Get method for element {}Tid
   */
  public java.lang.String getTid() {
    return this._f_Tid;
  }

  // Element field for element {}Aid
  private java.lang.String _f_Aid;
  /**
   * Set method for element {}Aid
   */
  public void setAid(java.lang.String _Aid) {
    this._f_Aid = _Aid;
  }
  /**
   * Get method for element {}Aid
   */
  public java.lang.String getAid() {
    return this._f_Aid;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof Alert)) return false;
    Alert typed = (Alert) object;
    if (this._f_Object != null) {
      if (typed._f_Object == null) return false;
      if (!this._f_Object.equals(typed._f_Object)) return false;
    } else {
      if (typed._f_Object != null) return false;
    }
    if (this._f_Attribute != null) {
      if (typed._f_Attribute == null) return false;
      if (!this._f_Attribute.equals(typed._f_Attribute)) return false;
    } else {
      if (typed._f_Attribute != null) return false;
    }
    if (this._f_Value != null) {
      if (typed._f_Value == null) return false;
      if (!this._f_Value.equals(typed._f_Value)) return false;
    } else {
      if (typed._f_Value != null) return false;
    }
    if (this._f_Description != null) {
      if (typed._f_Description == null) return false;
      if (!this._f_Description.equals(typed._f_Description)) return false;
    } else {
      if (typed._f_Description != null) return false;
    }
    if (this._f_Time != null) {
      if (typed._f_Time == null) return false;
      if (!this._f_Time.equals(typed._f_Time)) return false;
    } else {
      if (typed._f_Time != null) return false;
    }
    if (this._f_Tid != null) {
      if (typed._f_Tid == null) return false;
      if (!this._f_Tid.equals(typed._f_Tid)) return false;
    } else {
      if (typed._f_Tid != null) return false;
    }
    if (this._f_Aid != null) {
      if (typed._f_Aid == null) return false;
      if (!this._f_Aid.equals(typed._f_Aid)) return false;
    } else {
      if (typed._f_Aid != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Object != null) {
      result+= this._f_Object.hashCode();
    }
    if (this._f_Attribute != null) {
      result+= this._f_Attribute.hashCode();
    }
    if (this._f_Value != null) {
      result+= this._f_Value.hashCode();
    }
    if (this._f_Description != null) {
      result+= this._f_Description.hashCode();
    }
    if (this._f_Time != null) {
      result+= this._f_Time.hashCode();
    }
    if (this._f_Tid != null) {
      result+= this._f_Tid.hashCode();
    }
    if (this._f_Aid != null) {
      result+= this._f_Aid.hashCode();
    }
    return result;
  }
}
