/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon May 29 10:14:50 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.sapcontrol.client.types;

/**
 * Schema complexType Java representation.
 * Represents type of namespace {urn:SAPControl} anonymous with xpath [/definitions/types/schema/element[18]/complexType]
 */
public  class GetAlertsResponse implements java.io.Serializable {

  // Element field for element {}RootTidName
  private java.lang.String _f_RootTidName;
  /**
   * Set method for element {}RootTidName
   */
  public void setRootTidName(java.lang.String _RootTidName) {
    this._f_RootTidName = _RootTidName;
  }
  /**
   * Get method for element {}RootTidName
   */
  public java.lang.String getRootTidName() {
    return this._f_RootTidName;
  }

  // Element field for element {}alert
  private com.sap.sapcontrol.client.types.ArrayOfAlert _f_Alert;
  /**
   * Set method for element {}alert
   */
  public void setAlert(com.sap.sapcontrol.client.types.ArrayOfAlert _Alert) {
    this._f_Alert = _Alert;
  }
  /**
   * Get method for element {}alert
   */
  public com.sap.sapcontrol.client.types.ArrayOfAlert getAlert() {
    return this._f_Alert;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof GetAlertsResponse)) return false;
    GetAlertsResponse typed = (GetAlertsResponse) object;
    if (this._f_RootTidName != null) {
      if (typed._f_RootTidName == null) return false;
      if (!this._f_RootTidName.equals(typed._f_RootTidName)) return false;
    } else {
      if (typed._f_RootTidName != null) return false;
    }
    if (this._f_Alert != null) {
      if (typed._f_Alert == null) return false;
      if (!this._f_Alert.equals(typed._f_Alert)) return false;
    } else {
      if (typed._f_Alert != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_RootTidName != null) {
      result+= this._f_RootTidName.hashCode();
    }
    if (this._f_Alert != null) {
      result+= this._f_Alert.hashCode();
    }
    return result;
  }
}
