/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon May 29 10:14:50 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.sapcontrol.client.types;

/**
 * Schema complexType Java representation.
 * Represents type {urn:SAPControl}HeapInfo
 */
public  class HeapInfo implements java.io.Serializable {

  // Element field for element {}processname
  private java.lang.String _f_Processname;
  /**
   * Set method for element {}processname
   */
  public void setProcessname(java.lang.String _Processname) {
    this._f_Processname = _Processname;
  }
  /**
   * Get method for element {}processname
   */
  public java.lang.String getProcessname() {
    return this._f_Processname;
  }

  // Element field for element {}type
  private java.lang.String _f_Type;
  /**
   * Set method for element {}type
   */
  public void setType(java.lang.String _Type) {
    this._f_Type = _Type;
  }
  /**
   * Get method for element {}type
   */
  public java.lang.String getType() {
    return this._f_Type;
  }

  // Element field for element {}size
  private long _f_Size;
  /**
   * Set method for element {}size
   */
  public void setSize(long _Size) {
    this._f_Size = _Size;
  }
  /**
   * Get method for element {}size
   */
  public long getSize() {
    return this._f_Size;
  }

  // Element field for element {}commitSize
  private long _f_CommitSize;
  /**
   * Set method for element {}commitSize
   */
  public void setCommitSize(long _CommitSize) {
    this._f_CommitSize = _CommitSize;
  }
  /**
   * Get method for element {}commitSize
   */
  public long getCommitSize() {
    return this._f_CommitSize;
  }

  // Element field for element {}maxUsedSize
  private long _f_MaxUsedSize;
  /**
   * Set method for element {}maxUsedSize
   */
  public void setMaxUsedSize(long _MaxUsedSize) {
    this._f_MaxUsedSize = _MaxUsedSize;
  }
  /**
   * Get method for element {}maxUsedSize
   */
  public long getMaxUsedSize() {
    return this._f_MaxUsedSize;
  }

  // Element field for element {}initialSize
  private long _f_InitialSize;
  /**
   * Set method for element {}initialSize
   */
  public void setInitialSize(long _InitialSize) {
    this._f_InitialSize = _InitialSize;
  }
  /**
   * Get method for element {}initialSize
   */
  public long getInitialSize() {
    return this._f_InitialSize;
  }

  // Element field for element {}maxSize
  private long _f_MaxSize;
  /**
   * Set method for element {}maxSize
   */
  public void setMaxSize(long _MaxSize) {
    this._f_MaxSize = _MaxSize;
  }
  /**
   * Get method for element {}maxSize
   */
  public long getMaxSize() {
    return this._f_MaxSize;
  }

  // Element field for element {}dispstatus
  private com.sap.sapcontrol.client.types.STATECOLOR _f_Dispstatus;
  /**
   * Set method for element {}dispstatus
   */
  public void setDispstatus(com.sap.sapcontrol.client.types.STATECOLOR _Dispstatus) {
    this._f_Dispstatus = _Dispstatus;
  }
  /**
   * Get method for element {}dispstatus
   */
  public com.sap.sapcontrol.client.types.STATECOLOR getDispstatus() {
    return this._f_Dispstatus;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof HeapInfo)) return false;
    HeapInfo typed = (HeapInfo) object;
    if (this._f_Processname != null) {
      if (typed._f_Processname == null) return false;
      if (!this._f_Processname.equals(typed._f_Processname)) return false;
    } else {
      if (typed._f_Processname != null) return false;
    }
    if (this._f_Type != null) {
      if (typed._f_Type == null) return false;
      if (!this._f_Type.equals(typed._f_Type)) return false;
    } else {
      if (typed._f_Type != null) return false;
    }
    if (this._f_Size != typed._f_Size) return false;
    if (this._f_CommitSize != typed._f_CommitSize) return false;
    if (this._f_MaxUsedSize != typed._f_MaxUsedSize) return false;
    if (this._f_InitialSize != typed._f_InitialSize) return false;
    if (this._f_MaxSize != typed._f_MaxSize) return false;
    if (this._f_Dispstatus != null) {
      if (typed._f_Dispstatus == null) return false;
      if (!this._f_Dispstatus.equals(typed._f_Dispstatus)) return false;
    } else {
      if (typed._f_Dispstatus != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Processname != null) {
      result+= this._f_Processname.hashCode();
    }
    if (this._f_Type != null) {
      result+= this._f_Type.hashCode();
    }
    result+= (int) this._f_Size;
    result+= (int) this._f_CommitSize;
    result+= (int) this._f_MaxUsedSize;
    result+= (int) this._f_InitialSize;
    result+= (int) this._f_MaxSize;
    if (this._f_Dispstatus != null) {
      result+= this._f_Dispstatus.hashCode();
    }
    return result;
  }
}
