/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon May 29 10:14:50 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.sapcontrol.client.types;

/**
 * Schema complexType Java representation.
 * Represents type {urn:SAPControl}InstanceVersionInfo
 */
public  class InstanceVersionInfo implements java.io.Serializable {

  // Element field for element {}Filename
  private java.lang.String _f_Filename;
  /**
   * Set method for element {}Filename
   */
  public void setFilename(java.lang.String _Filename) {
    this._f_Filename = _Filename;
  }
  /**
   * Get method for element {}Filename
   */
  public java.lang.String getFilename() {
    return this._f_Filename;
  }

  // Element field for element {}VersionInfo
  private java.lang.String _f_VersionInfo;
  /**
   * Set method for element {}VersionInfo
   */
  public void setVersionInfo(java.lang.String _VersionInfo) {
    this._f_VersionInfo = _VersionInfo;
  }
  /**
   * Get method for element {}VersionInfo
   */
  public java.lang.String getVersionInfo() {
    return this._f_VersionInfo;
  }

  // Element field for element {}Time
  private java.lang.String _f_Time;
  /**
   * Set method for element {}Time
   */
  public void setTime(java.lang.String _Time) {
    this._f_Time = _Time;
  }
  /**
   * Get method for element {}Time
   */
  public java.lang.String getTime() {
    return this._f_Time;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof InstanceVersionInfo)) return false;
    InstanceVersionInfo typed = (InstanceVersionInfo) object;
    if (this._f_Filename != null) {
      if (typed._f_Filename == null) return false;
      if (!this._f_Filename.equals(typed._f_Filename)) return false;
    } else {
      if (typed._f_Filename != null) return false;
    }
    if (this._f_VersionInfo != null) {
      if (typed._f_VersionInfo == null) return false;
      if (!this._f_VersionInfo.equals(typed._f_VersionInfo)) return false;
    } else {
      if (typed._f_VersionInfo != null) return false;
    }
    if (this._f_Time != null) {
      if (typed._f_Time == null) return false;
      if (!this._f_Time.equals(typed._f_Time)) return false;
    } else {
      if (typed._f_Time != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Filename != null) {
      result+= this._f_Filename.hashCode();
    }
    if (this._f_VersionInfo != null) {
      result+= this._f_VersionInfo.hashCode();
    }
    if (this._f_Time != null) {
      result+= this._f_Time.hashCode();
    }
    return result;
  }
}
