/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon May 29 10:14:50 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.sapcontrol.client.types;

/**
 * Schema complexType Java representation.
 * Represents type of namespace {urn:SAPControl} anonymous with xpath [/definitions/types/schema/element[74]/complexType]
 */
public  class J2EEGetVMGCHistory2Response implements java.io.Serializable {

  // Element field for element {}gc
  private com.sap.sapcontrol.client.types.ArrayOfGCInfo2 _f_Gc;
  /**
   * Set method for element {}gc
   */
  public void setGc(com.sap.sapcontrol.client.types.ArrayOfGCInfo2 _Gc) {
    this._f_Gc = _Gc;
  }
  /**
   * Get method for element {}gc
   */
  public com.sap.sapcontrol.client.types.ArrayOfGCInfo2 getGc() {
    return this._f_Gc;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof J2EEGetVMGCHistory2Response)) return false;
    J2EEGetVMGCHistory2Response typed = (J2EEGetVMGCHistory2Response) object;
    if (this._f_Gc != null) {
      if (typed._f_Gc == null) return false;
      if (!this._f_Gc.equals(typed._f_Gc)) return false;
    } else {
      if (typed._f_Gc != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Gc != null) {
      result+= this._f_Gc.hashCode();
    }
    return result;
  }
}
