/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon May 29 10:14:50 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.sapcontrol.client.types;

/**
 * Schema complexType Java representation.
 * Represents type {urn:SAPControl}J2EERemoteObject
 */
public  class J2EERemoteObject implements java.io.Serializable {

  // Element field for element {}IdHash
  private int _f_IdHash;
  /**
   * Set method for element {}IdHash
   */
  public void setIdHash(int _IdHash) {
    this._f_IdHash = _IdHash;
  }
  /**
   * Get method for element {}IdHash
   */
  public int getIdHash() {
    return this._f_IdHash;
  }

  // Element field for element {}address
  private java.lang.String _f_Address;
  /**
   * Set method for element {}address
   */
  public void setAddress(java.lang.String _Address) {
    this._f_Address = _Address;
  }
  /**
   * Get method for element {}address
   */
  public java.lang.String getAddress() {
    return this._f_Address;
  }

  // Element field for element {}port
  private int _f_Port;
  /**
   * Set method for element {}port
   */
  public void setPort(int _Port) {
    this._f_Port = _Port;
  }
  /**
   * Get method for element {}port
   */
  public int getPort() {
    return this._f_Port;
  }

  // Element field for element {}protocol
  private java.lang.String _f_Protocol;
  /**
   * Set method for element {}protocol
   */
  public void setProtocol(java.lang.String _Protocol) {
    this._f_Protocol = _Protocol;
  }
  /**
   * Get method for element {}protocol
   */
  public java.lang.String getProtocol() {
    return this._f_Protocol;
  }

  // Element field for element {}direction
  private java.lang.String _f_Direction;
  /**
   * Set method for element {}direction
   */
  public void setDirection(java.lang.String _Direction) {
    this._f_Direction = _Direction;
  }
  /**
   * Get method for element {}direction
   */
  public java.lang.String getDirection() {
    return this._f_Direction;
  }

  // Element field for element {}stubs
  private int _f_Stubs;
  /**
   * Set method for element {}stubs
   */
  public void setStubs(int _Stubs) {
    this._f_Stubs = _Stubs;
  }
  /**
   * Get method for element {}stubs
   */
  public int getStubs() {
    return this._f_Stubs;
  }

  // Element field for element {}implementations
  private int _f_Implementations;
  /**
   * Set method for element {}implementations
   */
  public void setImplementations(int _Implementations) {
    this._f_Implementations = _Implementations;
  }
  /**
   * Get method for element {}implementations
   */
  public int getImplementations() {
    return this._f_Implementations;
  }

  // Element field for element {}creationTime
  private java.lang.String _f_CreationTime;
  /**
   * Set method for element {}creationTime
   */
  public void setCreationTime(java.lang.String _CreationTime) {
    this._f_CreationTime = _CreationTime;
  }
  /**
   * Get method for element {}creationTime
   */
  public java.lang.String getCreationTime() {
    return this._f_CreationTime;
  }

  // Element field for element {}updateTime
  private java.lang.String _f_UpdateTime;
  /**
   * Set method for element {}updateTime
   */
  public void setUpdateTime(java.lang.String _UpdateTime) {
    this._f_UpdateTime = _UpdateTime;
  }
  /**
   * Get method for element {}updateTime
   */
  public java.lang.String getUpdateTime() {
    return this._f_UpdateTime;
  }

  // Element field for element {}processname
  private java.lang.String _f_Processname;
  /**
   * Set method for element {}processname
   */
  public void setProcessname(java.lang.String _Processname) {
    this._f_Processname = _Processname;
  }
  /**
   * Get method for element {}processname
   */
  public java.lang.String getProcessname() {
    return this._f_Processname;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof J2EERemoteObject)) return false;
    J2EERemoteObject typed = (J2EERemoteObject) object;
    if (this._f_IdHash != typed._f_IdHash) return false;
    if (this._f_Address != null) {
      if (typed._f_Address == null) return false;
      if (!this._f_Address.equals(typed._f_Address)) return false;
    } else {
      if (typed._f_Address != null) return false;
    }
    if (this._f_Port != typed._f_Port) return false;
    if (this._f_Protocol != null) {
      if (typed._f_Protocol == null) return false;
      if (!this._f_Protocol.equals(typed._f_Protocol)) return false;
    } else {
      if (typed._f_Protocol != null) return false;
    }
    if (this._f_Direction != null) {
      if (typed._f_Direction == null) return false;
      if (!this._f_Direction.equals(typed._f_Direction)) return false;
    } else {
      if (typed._f_Direction != null) return false;
    }
    if (this._f_Stubs != typed._f_Stubs) return false;
    if (this._f_Implementations != typed._f_Implementations) return false;
    if (this._f_CreationTime != null) {
      if (typed._f_CreationTime == null) return false;
      if (!this._f_CreationTime.equals(typed._f_CreationTime)) return false;
    } else {
      if (typed._f_CreationTime != null) return false;
    }
    if (this._f_UpdateTime != null) {
      if (typed._f_UpdateTime == null) return false;
      if (!this._f_UpdateTime.equals(typed._f_UpdateTime)) return false;
    } else {
      if (typed._f_UpdateTime != null) return false;
    }
    if (this._f_Processname != null) {
      if (typed._f_Processname == null) return false;
      if (!this._f_Processname.equals(typed._f_Processname)) return false;
    } else {
      if (typed._f_Processname != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    result+= (int) this._f_IdHash;
    if (this._f_Address != null) {
      result+= this._f_Address.hashCode();
    }
    result+= (int) this._f_Port;
    if (this._f_Protocol != null) {
      result+= this._f_Protocol.hashCode();
    }
    if (this._f_Direction != null) {
      result+= this._f_Direction.hashCode();
    }
    result+= (int) this._f_Stubs;
    result+= (int) this._f_Implementations;
    if (this._f_CreationTime != null) {
      result+= this._f_CreationTime.hashCode();
    }
    if (this._f_UpdateTime != null) {
      result+= this._f_UpdateTime.hashCode();
    }
    if (this._f_Processname != null) {
      result+= this._f_Processname.hashCode();
    }
    return result;
  }
}
