/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon May 29 10:14:50 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.sapcontrol.client.types;

/**
 * Schema complexType Java representation.
 * Represents type {urn:SAPControl}J2EESharedTableInfo
 */
public  class J2EESharedTableInfo implements java.io.Serializable {

  // Element field for element {}table
  private java.lang.String _f_Table;
  /**
   * Set method for element {}table
   */
  public void setTable(java.lang.String _Table) {
    this._f_Table = _Table;
  }
  /**
   * Get method for element {}table
   */
  public java.lang.String getTable() {
    return this._f_Table;
  }

  // Element field for element {}used
  private int _f_Used;
  /**
   * Set method for element {}used
   */
  public void setUsed(int _Used) {
    this._f_Used = _Used;
  }
  /**
   * Get method for element {}used
   */
  public int getUsed() {
    return this._f_Used;
  }

  // Element field for element {}peak
  private int _f_Peak;
  /**
   * Set method for element {}peak
   */
  public void setPeak(int _Peak) {
    this._f_Peak = _Peak;
  }
  /**
   * Get method for element {}peak
   */
  public int getPeak() {
    return this._f_Peak;
  }

  // Element field for element {}limit
  private int _f_Limit;
  /**
   * Set method for element {}limit
   */
  public void setLimit(int _Limit) {
    this._f_Limit = _Limit;
  }
  /**
   * Get method for element {}limit
   */
  public int getLimit() {
    return this._f_Limit;
  }

  // Element field for element {}dispstatus
  private com.sap.sapcontrol.client.types.STATECOLOR _f_Dispstatus;
  /**
   * Set method for element {}dispstatus
   */
  public void setDispstatus(com.sap.sapcontrol.client.types.STATECOLOR _Dispstatus) {
    this._f_Dispstatus = _Dispstatus;
  }
  /**
   * Get method for element {}dispstatus
   */
  public com.sap.sapcontrol.client.types.STATECOLOR getDispstatus() {
    return this._f_Dispstatus;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof J2EESharedTableInfo)) return false;
    J2EESharedTableInfo typed = (J2EESharedTableInfo) object;
    if (this._f_Table != null) {
      if (typed._f_Table == null) return false;
      if (!this._f_Table.equals(typed._f_Table)) return false;
    } else {
      if (typed._f_Table != null) return false;
    }
    if (this._f_Used != typed._f_Used) return false;
    if (this._f_Peak != typed._f_Peak) return false;
    if (this._f_Limit != typed._f_Limit) return false;
    if (this._f_Dispstatus != null) {
      if (typed._f_Dispstatus == null) return false;
      if (!this._f_Dispstatus.equals(typed._f_Dispstatus)) return false;
    } else {
      if (typed._f_Dispstatus != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Table != null) {
      result+= this._f_Table.hashCode();
    }
    result+= (int) this._f_Used;
    result+= (int) this._f_Peak;
    result+= (int) this._f_Limit;
    if (this._f_Dispstatus != null) {
      result+= this._f_Dispstatus.hashCode();
    }
    return result;
  }
}
