/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon May 29 10:14:50 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.sapcontrol.client.types;

/**
 * Schema complexType Java representation.
 * Represents type of namespace {urn:SAPControl} anonymous with xpath [/definitions/types/schema/element[62]/complexType]
 */
public  class J2EEGetSessionListResponse implements java.io.Serializable {

  // Element field for element {}session
  private com.sap.sapcontrol.client.types.ArrayOfJ2EESession _f_Session;
  /**
   * Set method for element {}session
   */
  public void setSession(com.sap.sapcontrol.client.types.ArrayOfJ2EESession _Session) {
    this._f_Session = _Session;
  }
  /**
   * Get method for element {}session
   */
  public com.sap.sapcontrol.client.types.ArrayOfJ2EESession getSession() {
    return this._f_Session;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof J2EEGetSessionListResponse)) return false;
    J2EEGetSessionListResponse typed = (J2EEGetSessionListResponse) object;
    if (this._f_Session != null) {
      if (typed._f_Session == null) return false;
      if (!this._f_Session.equals(typed._f_Session)) return false;
    } else {
      if (typed._f_Session != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Session != null) {
      result+= this._f_Session.hashCode();
    }
    return result;
  }
}
