/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon May 29 10:14:50 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.sapcontrol.client.types;

/**
 * Schema complexType Java representation.
 * Represents type {urn:SAPControl}J2EECache2
 */
public  class J2EECache2 implements java.io.Serializable {

  // Element field for element {}description
  private java.lang.String _f_Description;
  /**
   * Set method for element {}description
   */
  public void setDescription(java.lang.String _Description) {
    this._f_Description = _Description;
  }
  /**
   * Get method for element {}description
   */
  public java.lang.String getDescription() {
    return this._f_Description;
  }

  // Element field for element {}owner
  private java.lang.String _f_Owner;
  /**
   * Set method for element {}owner
   */
  public void setOwner(java.lang.String _Owner) {
    this._f_Owner = _Owner;
  }
  /**
   * Get method for element {}owner
   */
  public java.lang.String getOwner() {
    return this._f_Owner;
  }

  // Element field for element {}processname
  private java.lang.String _f_Processname;
  /**
   * Set method for element {}processname
   */
  public void setProcessname(java.lang.String _Processname) {
    this._f_Processname = _Processname;
  }
  /**
   * Get method for element {}processname
   */
  public java.lang.String getProcessname() {
    return this._f_Processname;
  }

  // Element field for element {}type
  private java.lang.String _f_Type;
  /**
   * Set method for element {}type
   */
  public void setType(java.lang.String _Type) {
    this._f_Type = _Type;
  }
  /**
   * Get method for element {}type
   */
  public java.lang.String getType() {
    return this._f_Type;
  }

  // Element field for element {}size
  private long _f_Size;
  /**
   * Set method for element {}size
   */
  public void setSize(long _Size) {
    this._f_Size = _Size;
  }
  /**
   * Get method for element {}size
   */
  public long getSize() {
    return this._f_Size;
  }

  // Element field for element {}attrSize
  private long _f_AttrSize;
  /**
   * Set method for element {}attrSize
   */
  public void setAttrSize(long _AttrSize) {
    this._f_AttrSize = _AttrSize;
  }
  /**
   * Get method for element {}attrSize
   */
  public long getAttrSize() {
    return this._f_AttrSize;
  }

  // Element field for element {}keysSize
  private long _f_KeysSize;
  /**
   * Set method for element {}keysSize
   */
  public void setKeysSize(long _KeysSize) {
    this._f_KeysSize = _KeysSize;
  }
  /**
   * Get method for element {}keysSize
   */
  public long getKeysSize() {
    return this._f_KeysSize;
  }

  // Element field for element {}cachedObjects
  private int _f_CachedObjects;
  /**
   * Set method for element {}cachedObjects
   */
  public void setCachedObjects(int _CachedObjects) {
    this._f_CachedObjects = _CachedObjects;
  }
  /**
   * Get method for element {}cachedObjects
   */
  public int getCachedObjects() {
    return this._f_CachedObjects;
  }

  // Element field for element {}usedObjects
  private int _f_UsedObjects;
  /**
   * Set method for element {}usedObjects
   */
  public void setUsedObjects(int _UsedObjects) {
    this._f_UsedObjects = _UsedObjects;
  }
  /**
   * Get method for element {}usedObjects
   */
  public int getUsedObjects() {
    return this._f_UsedObjects;
  }

  // Element field for element {}puts
  private int _f_Puts;
  /**
   * Set method for element {}puts
   */
  public void setPuts(int _Puts) {
    this._f_Puts = _Puts;
  }
  /**
   * Get method for element {}puts
   */
  public int getPuts() {
    return this._f_Puts;
  }

  // Element field for element {}gets
  private int _f_Gets;
  /**
   * Set method for element {}gets
   */
  public void setGets(int _Gets) {
    this._f_Gets = _Gets;
  }
  /**
   * Get method for element {}gets
   */
  public int getGets() {
    return this._f_Gets;
  }

  // Element field for element {}hits
  private int _f_Hits;
  /**
   * Set method for element {}hits
   */
  public void setHits(int _Hits) {
    this._f_Hits = _Hits;
  }
  /**
   * Get method for element {}hits
   */
  public int getHits() {
    return this._f_Hits;
  }

  // Element field for element {}changes
  private int _f_Changes;
  /**
   * Set method for element {}changes
   */
  public void setChanges(int _Changes) {
    this._f_Changes = _Changes;
  }
  /**
   * Get method for element {}changes
   */
  public int getChanges() {
    return this._f_Changes;
  }

  // Element field for element {}removes
  private int _f_Removes;
  /**
   * Set method for element {}removes
   */
  public void setRemoves(int _Removes) {
    this._f_Removes = _Removes;
  }
  /**
   * Get method for element {}removes
   */
  public int getRemoves() {
    return this._f_Removes;
  }

  // Element field for element {}evictions
  private int _f_Evictions;
  /**
   * Set method for element {}evictions
   */
  public void setEvictions(int _Evictions) {
    this._f_Evictions = _Evictions;
  }
  /**
   * Get method for element {}evictions
   */
  public int getEvictions() {
    return this._f_Evictions;
  }

  // Element field for element {}instanceInvalidations
  private int _f_InstanceInvalidations;
  /**
   * Set method for element {}instanceInvalidations
   */
  public void setInstanceInvalidations(int _InstanceInvalidations) {
    this._f_InstanceInvalidations = _InstanceInvalidations;
  }
  /**
   * Get method for element {}instanceInvalidations
   */
  public int getInstanceInvalidations() {
    return this._f_InstanceInvalidations;
  }

  // Element field for element {}clusterInvalidations
  private int _f_ClusterInvalidations;
  /**
   * Set method for element {}clusterInvalidations
   */
  public void setClusterInvalidations(int _ClusterInvalidations) {
    this._f_ClusterInvalidations = _ClusterInvalidations;
  }
  /**
   * Get method for element {}clusterInvalidations
   */
  public int getClusterInvalidations() {
    return this._f_ClusterInvalidations;
  }

  // Element field for element {}updateTime
  private java.lang.String _f_UpdateTime;
  /**
   * Set method for element {}updateTime
   */
  public void setUpdateTime(java.lang.String _UpdateTime) {
    this._f_UpdateTime = _UpdateTime;
  }
  /**
   * Get method for element {}updateTime
   */
  public java.lang.String getUpdateTime() {
    return this._f_UpdateTime;
  }

  // Element field for element {}dispstatus
  private com.sap.sapcontrol.client.types.STATECOLOR _f_Dispstatus;
  /**
   * Set method for element {}dispstatus
   */
  public void setDispstatus(com.sap.sapcontrol.client.types.STATECOLOR _Dispstatus) {
    this._f_Dispstatus = _Dispstatus;
  }
  /**
   * Get method for element {}dispstatus
   */
  public com.sap.sapcontrol.client.types.STATECOLOR getDispstatus() {
    return this._f_Dispstatus;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof J2EECache2)) return false;
    J2EECache2 typed = (J2EECache2) object;
    if (this._f_Description != null) {
      if (typed._f_Description == null) return false;
      if (!this._f_Description.equals(typed._f_Description)) return false;
    } else {
      if (typed._f_Description != null) return false;
    }
    if (this._f_Owner != null) {
      if (typed._f_Owner == null) return false;
      if (!this._f_Owner.equals(typed._f_Owner)) return false;
    } else {
      if (typed._f_Owner != null) return false;
    }
    if (this._f_Processname != null) {
      if (typed._f_Processname == null) return false;
      if (!this._f_Processname.equals(typed._f_Processname)) return false;
    } else {
      if (typed._f_Processname != null) return false;
    }
    if (this._f_Type != null) {
      if (typed._f_Type == null) return false;
      if (!this._f_Type.equals(typed._f_Type)) return false;
    } else {
      if (typed._f_Type != null) return false;
    }
    if (this._f_Size != typed._f_Size) return false;
    if (this._f_AttrSize != typed._f_AttrSize) return false;
    if (this._f_KeysSize != typed._f_KeysSize) return false;
    if (this._f_CachedObjects != typed._f_CachedObjects) return false;
    if (this._f_UsedObjects != typed._f_UsedObjects) return false;
    if (this._f_Puts != typed._f_Puts) return false;
    if (this._f_Gets != typed._f_Gets) return false;
    if (this._f_Hits != typed._f_Hits) return false;
    if (this._f_Changes != typed._f_Changes) return false;
    if (this._f_Removes != typed._f_Removes) return false;
    if (this._f_Evictions != typed._f_Evictions) return false;
    if (this._f_InstanceInvalidations != typed._f_InstanceInvalidations) return false;
    if (this._f_ClusterInvalidations != typed._f_ClusterInvalidations) return false;
    if (this._f_UpdateTime != null) {
      if (typed._f_UpdateTime == null) return false;
      if (!this._f_UpdateTime.equals(typed._f_UpdateTime)) return false;
    } else {
      if (typed._f_UpdateTime != null) return false;
    }
    if (this._f_Dispstatus != null) {
      if (typed._f_Dispstatus == null) return false;
      if (!this._f_Dispstatus.equals(typed._f_Dispstatus)) return false;
    } else {
      if (typed._f_Dispstatus != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Description != null) {
      result+= this._f_Description.hashCode();
    }
    if (this._f_Owner != null) {
      result+= this._f_Owner.hashCode();
    }
    if (this._f_Processname != null) {
      result+= this._f_Processname.hashCode();
    }
    if (this._f_Type != null) {
      result+= this._f_Type.hashCode();
    }
    result+= (int) this._f_Size;
    result+= (int) this._f_AttrSize;
    result+= (int) this._f_KeysSize;
    result+= (int) this._f_CachedObjects;
    result+= (int) this._f_UsedObjects;
    result+= (int) this._f_Puts;
    result+= (int) this._f_Gets;
    result+= (int) this._f_Hits;
    result+= (int) this._f_Changes;
    result+= (int) this._f_Removes;
    result+= (int) this._f_Evictions;
    result+= (int) this._f_InstanceInvalidations;
    result+= (int) this._f_ClusterInvalidations;
    if (this._f_UpdateTime != null) {
      result+= this._f_UpdateTime.hashCode();
    }
    if (this._f_Dispstatus != null) {
      result+= this._f_Dispstatus.hashCode();
    }
    return result;
  }
}
