/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon May 29 10:14:50 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.sapcontrol.client.types;

/**
 * Schema complexType Java representation.
 * Represents type of namespace {urn:SAPControl} anonymous with xpath [/definitions/types/schema/element[80]/complexType]
 */
public  class J2EEGetRemoteObjectListResponse implements java.io.Serializable {

  // Element field for element {}remoteobject
  private com.sap.sapcontrol.client.types.ArrayOfJ2EERemoteObject _f_Remoteobject;
  /**
   * Set method for element {}remoteobject
   */
  public void setRemoteobject(com.sap.sapcontrol.client.types.ArrayOfJ2EERemoteObject _Remoteobject) {
    this._f_Remoteobject = _Remoteobject;
  }
  /**
   * Get method for element {}remoteobject
   */
  public com.sap.sapcontrol.client.types.ArrayOfJ2EERemoteObject getRemoteobject() {
    return this._f_Remoteobject;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof J2EEGetRemoteObjectListResponse)) return false;
    J2EEGetRemoteObjectListResponse typed = (J2EEGetRemoteObjectListResponse) object;
    if (this._f_Remoteobject != null) {
      if (typed._f_Remoteobject == null) return false;
      if (!this._f_Remoteobject.equals(typed._f_Remoteobject)) return false;
    } else {
      if (typed._f_Remoteobject != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Remoteobject != null) {
      result+= this._f_Remoteobject.hashCode();
    }
    return result;
  }
}
