/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon May 29 10:14:50 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.sapcontrol.client.types;

/**
 * Schema complexType Java representation.
 * Represents type {urn:SAPControl}SyslogEntry
 */
public  class SyslogEntry implements java.io.Serializable {

  // Element field for element {}Time
  private java.lang.String _f_Time;
  /**
   * Set method for element {}Time
   */
  public void setTime(java.lang.String _Time) {
    this._f_Time = _Time;
  }
  /**
   * Get method for element {}Time
   */
  public java.lang.String getTime() {
    return this._f_Time;
  }

  // Element field for element {}Typ
  private java.lang.String _f_Typ;
  /**
   * Set method for element {}Typ
   */
  public void setTyp(java.lang.String _Typ) {
    this._f_Typ = _Typ;
  }
  /**
   * Get method for element {}Typ
   */
  public java.lang.String getTyp() {
    return this._f_Typ;
  }

  // Element field for element {}Client
  private java.lang.String _f_Client;
  /**
   * Set method for element {}Client
   */
  public void setClient(java.lang.String _Client) {
    this._f_Client = _Client;
  }
  /**
   * Get method for element {}Client
   */
  public java.lang.String getClient() {
    return this._f_Client;
  }

  // Element field for element {}User
  private java.lang.String _f_User;
  /**
   * Set method for element {}User
   */
  public void setUser(java.lang.String _User) {
    this._f_User = _User;
  }
  /**
   * Get method for element {}User
   */
  public java.lang.String getUser() {
    return this._f_User;
  }

  // Element field for element {}Tcode
  private java.lang.String _f_Tcode;
  /**
   * Set method for element {}Tcode
   */
  public void setTcode(java.lang.String _Tcode) {
    this._f_Tcode = _Tcode;
  }
  /**
   * Get method for element {}Tcode
   */
  public java.lang.String getTcode() {
    return this._f_Tcode;
  }

  // Element field for element {}MNo
  private java.lang.String _f_MNo;
  /**
   * Set method for element {}MNo
   */
  public void setMNo(java.lang.String _MNo) {
    this._f_MNo = _MNo;
  }
  /**
   * Get method for element {}MNo
   */
  public java.lang.String getMNo() {
    return this._f_MNo;
  }

  // Element field for element {}Text
  private java.lang.String _f_Text;
  /**
   * Set method for element {}Text
   */
  public void setText(java.lang.String _Text) {
    this._f_Text = _Text;
  }
  /**
   * Get method for element {}Text
   */
  public java.lang.String getText() {
    return this._f_Text;
  }

  // Element field for element {}Severity
  private com.sap.sapcontrol.client.types.STATECOLOR _f_Severity;
  /**
   * Set method for element {}Severity
   */
  public void setSeverity(com.sap.sapcontrol.client.types.STATECOLOR _Severity) {
    this._f_Severity = _Severity;
  }
  /**
   * Get method for element {}Severity
   */
  public com.sap.sapcontrol.client.types.STATECOLOR getSeverity() {
    return this._f_Severity;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof SyslogEntry)) return false;
    SyslogEntry typed = (SyslogEntry) object;
    if (this._f_Time != null) {
      if (typed._f_Time == null) return false;
      if (!this._f_Time.equals(typed._f_Time)) return false;
    } else {
      if (typed._f_Time != null) return false;
    }
    if (this._f_Typ != null) {
      if (typed._f_Typ == null) return false;
      if (!this._f_Typ.equals(typed._f_Typ)) return false;
    } else {
      if (typed._f_Typ != null) return false;
    }
    if (this._f_Client != null) {
      if (typed._f_Client == null) return false;
      if (!this._f_Client.equals(typed._f_Client)) return false;
    } else {
      if (typed._f_Client != null) return false;
    }
    if (this._f_User != null) {
      if (typed._f_User == null) return false;
      if (!this._f_User.equals(typed._f_User)) return false;
    } else {
      if (typed._f_User != null) return false;
    }
    if (this._f_Tcode != null) {
      if (typed._f_Tcode == null) return false;
      if (!this._f_Tcode.equals(typed._f_Tcode)) return false;
    } else {
      if (typed._f_Tcode != null) return false;
    }
    if (this._f_MNo != null) {
      if (typed._f_MNo == null) return false;
      if (!this._f_MNo.equals(typed._f_MNo)) return false;
    } else {
      if (typed._f_MNo != null) return false;
    }
    if (this._f_Text != null) {
      if (typed._f_Text == null) return false;
      if (!this._f_Text.equals(typed._f_Text)) return false;
    } else {
      if (typed._f_Text != null) return false;
    }
    if (this._f_Severity != null) {
      if (typed._f_Severity == null) return false;
      if (!this._f_Severity.equals(typed._f_Severity)) return false;
    } else {
      if (typed._f_Severity != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._f_Time != null) {
      result+= this._f_Time.hashCode();
    }
    if (this._f_Typ != null) {
      result+= this._f_Typ.hashCode();
    }
    if (this._f_Client != null) {
      result+= this._f_Client.hashCode();
    }
    if (this._f_User != null) {
      result+= this._f_User.hashCode();
    }
    if (this._f_Tcode != null) {
      result+= this._f_Tcode.hashCode();
    }
    if (this._f_MNo != null) {
      result+= this._f_MNo.hashCode();
    }
    if (this._f_Text != null) {
      result+= this._f_Text.hashCode();
    }
    if (this._f_Severity != null) {
      result+= this._f_Severity.hashCode();
    }
    return result;
  }
}
