/*
 * Copyright (c) 2004 Standard Performance Evaluation Corporation (SPEC)
 *               All rights reserved.
 *
 * This source code is provided as is, without any express or implied warranty.
 *
 *  History:
 *  Date        ID, Company             Description
 *  ----------  ----------------        ----------------------------------------------
 *  2005/12/22  Bernhard Riedhofer, SAP Modified for the EJB3 version of SPECjAppServer2004
 */
package org.spec.jappserver.corp;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Version;

import org.spec.jappserver.corp.helper.CustomerInventoryDataBean;

/**
 * EJB3 equivalent for CustomerInventoryEnt
 */
@Entity
@Table(name = "C_CUSTOMERINVENTOR")
public class CustomerInventory
      implements Serializable
{
   private static final long serialVersionUID = 1L;

   @TableGenerator(
         name="customerInventory",
         table="U_SEQUENCES",
         pkColumnName="S_ID",
         valueColumnName="S_NEXTNUM",
         pkColumnValue="inventory",
         initialValue=1000000000,
         allocationSize=10000)

   // persistent
   @Id @Column(name = "CI_ID")
   @GeneratedValue(strategy=GenerationType.TABLE, generator="customerInventory")
   protected int customerInventoryId;

   @Basic @Column(name = "CI_QUANTITY")
   protected int quantity;

   @Basic @Column(name = "CI_ITEMID")
   protected String itemId;

   @Basic @Column(name = "CI_VALUE")
   protected BigDecimal value;

   @Version @Column(name = "CI_VERSION")
   private int version;

   // relationship
   @ManyToOne
   @JoinColumn(name="CI_CUSTOMERID")
   protected Customer customer;

   /**
    * Default constructor
    */
   public CustomerInventory ()
   {
   }

   /**
    * Constructor
    *
    * @param customer PCCustomer object
    * @param inventoryId Inventory identifier generated by SequenceSes
    * @param itemID Item identifier
    * @param quantity quantity value
    * @param totalValue totalValue
    * @param atomicityTest Atomicity test
    * @param sesCtx Session context
    */
   public CustomerInventory (Customer customer, String itemID, int quantity,
         BigDecimal totalValue)
   {
      setQuantity(quantity);
      setItemId(itemID);
      setValue(totalValue.setScale(2, BigDecimal.ROUND_UP));
      setCustomer(customer);
   }

   /**
    * Gets a customerinventory object from the type CustomerInventoryDataBean.
    *
    * @return CustomerInventoryDataBean object
    * @see org.spec.jappserver.corp.helper.CustomerInventoryDataBean
    */
   public CustomerInventoryDataBean getDataBean ()
   {
      CustomerInventoryDataBean cusDataBean = new CustomerInventoryDataBean();
      cusDataBean.setCustomerID(getCustomer().getCustomerId());
      cusDataBean.setQuantity(getQuantity());
      cusDataBean.setVehicle(getItemId());
      cusDataBean.setId(getCustomerInventoryId());
      cusDataBean.setTotalCost(getValue());
      return cusDataBean;
   }

   /**
    * Persistent field.
    *
    * @return customerInventoryId value
    */
   public int getCustomerInventoryId ()
   {
      return customerInventoryId;
   }

   /**
    * Persistent field.
    *
    * @return itemId value
    */
   public String getItemId ()
   {
      return itemId;
   }

   /**
    * Persistent field.
    *
    * @return quantity value
    */
   public int getQuantity ()
   {
      return quantity;
   }

   /**
    * Persistent field.
    *
    * @return value value
    */
   public BigDecimal getValue ()
   {
      return value;
   }

   /**
    * Persistent field.
    * Version column.
    *
    * @return version
    */
   public int getVersion()
   {
      return version;
   }

   /**
    * Persistent field.
    *
    * @param i customerInventoryId value
    */
   public void setCustomerInventoryId (int i)
   {
      customerInventoryId = i;
   }

   /**
    * Persistent field.
    * @param string itemId value
    */
   public void setItemId (String string)
   {
      itemId = string;
   }

   /**
    * Persistent field.
    * @param i quantity value
    */
   public void setQuantity (int i)
   {
      quantity = i;
   }

   /**
    * Persistent field.
    * @param decimal value value
    */
   public void setValue (BigDecimal decimal)
   {
      value = decimal;
   }

   /**
    * Persistent field.
    * Version column.
    *
    * @param int version
    */
   public void setVersion(int version)
   {
      this.version = version;
   }

   /**
    * Relationship.
    * @return customer value
    */
   public Customer getCustomer ()
   {
      return customer;
   }

   /**
    * Relationship.
    * @param customer customer value
    */
   public void setCustomer (Customer cust)
   {
      customer = cust;
   }
}
