/*
 * Generated by SAP SchemaToJava Generator NW05 on Fri Jun 01 12:58:39 EEST 2007
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.services.webservices.server.deploy.descriptors.ws;

/**
 * Enumeration Java representation.
 * Represents type {http://www.sap.com/webas/710/ws/webservices-j2ee-engine-descriptor}wsdlTypeType
 */
public class WsdlTypeType implements java.io.Serializable {

  private static final long serialVersionUID = -8173079851740041231L;

  public static final java.lang.String _binding = "binding";
  public static final java.lang.String _porttype = "porttype";
  public static final java.lang.String _root = "root";

  public static final WsdlTypeType binding = new WsdlTypeType(_binding);
  public static final WsdlTypeType porttype = new WsdlTypeType(_porttype);
  public static final WsdlTypeType root = new WsdlTypeType(_root);

  //  Enumeration Content
  protected java.lang.String _value;

  public WsdlTypeType(java.lang.String _value) {
    if (_binding.equals(_value)) {
      this._value = _value;
      return;
    }
    if (_porttype.equals(_value)) {
      this._value = _value;
      return;
    }
    if (_root.equals(_value)) {
      this._value = _value;
      return;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+_value+"] passed.");
  }

  public java.lang.String getValue() {
    return _value;
  }

  public static WsdlTypeType fromValue(java.lang.String value) {
    if (_binding.equals(value)) {
      return binding;
    }
    if (_porttype.equals(value)) {
      return porttype;
    }
    if (_root.equals(value)) {
      return root;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+value+"] passed.");
  }

  public static WsdlTypeType fromString(String value) {
    if ("binding".equals(value)) {
      return binding;
    }
    if ("porttype".equals(value)) {
      return porttype;
    }
    if ("root".equals(value)) {
      return root;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+value+"] passed.");
  }

  public java.lang.String toString() {
    if (_binding.equals(_value)) {
      return "binding";
    }
    if (_porttype.equals(_value)) {
      return "porttype";
    }
    if (_root.equals(_value)) {
      return "root";
    }
    return java.lang.String.valueOf(_value);
  }

  public boolean equals(java.lang.Object obj) {
    if (obj != null) {
      if (obj instanceof WsdlTypeType) {
        if (_value.equals(((WsdlTypeType)obj)._value)) {
          return true;
        }
      }
    }
    return false;
  }

  public int hashCode() {
    return this._value.hashCode();
  }

}
