/*
 * Generated by SAP SchemaToJava Generator NW05 on Fri Jun 01 12:58:39 EEST 2007
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.services.webservices.server.deploy.descriptors.ws;

/**
 * Enumeration Java representation.
 * Represents type {http://www.sap.com/webas/710/ws/webservices-j2ee-engine-descriptor}wsdlStyleType
 */
public class WsdlStyleType implements java.io.Serializable {

  private static final long serialVersionUID = -1558905430942867028L;

  public static final java.lang.String _document = "document";
  public static final java.lang.String _rpc = "rpc";
  public static final java.lang.String _rpc_enc = "rpc_enc";
  public static final java.lang.String _defaultTemp = "default";

  public static final WsdlStyleType document = new WsdlStyleType(_document);
  public static final WsdlStyleType rpc = new WsdlStyleType(_rpc);
  public static final WsdlStyleType rpc_enc = new WsdlStyleType(_rpc_enc);
  public static final WsdlStyleType defaultTemp = new WsdlStyleType(_defaultTemp);

  //  Enumeration Content
  protected java.lang.String _value;

  public WsdlStyleType(java.lang.String _value) {
    if (_document.equals(_value)) {
      this._value = _value;
      return;
    }
    if (_rpc.equals(_value)) {
      this._value = _value;
      return;
    }
    if (_rpc_enc.equals(_value)) {
      this._value = _value;
      return;
    }
    if (_defaultTemp.equals(_value)) {
      this._value = _value;
      return;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+_value+"] passed.");
  }

  public java.lang.String getValue() {
    return _value;
  }

  public static WsdlStyleType fromValue(java.lang.String value) {
    if (_document.equals(value)) {
      return document;
    }
    if (_rpc.equals(value)) {
      return rpc;
    }
    if (_rpc_enc.equals(value)) {
      return rpc_enc;
    }
    if (_defaultTemp.equals(value)) {
      return defaultTemp;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+value+"] passed.");
  }

  public static WsdlStyleType fromString(String value) {
    if ("document".equals(value)) {
      return document;
    }
    if ("rpc".equals(value)) {
      return rpc;
    }
    if ("rpc_enc".equals(value)) {
      return rpc_enc;
    }
    if ("default".equals(value)) {
      return defaultTemp;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+value+"] passed.");
  }

  public java.lang.String toString() {
    if (_document.equals(_value)) {
      return "document";
    }
    if (_rpc.equals(_value)) {
      return "rpc";
    }
    if (_rpc_enc.equals(_value)) {
      return "rpc_enc";
    }
    if (_defaultTemp.equals(_value)) {
      return "default";
    }
    return java.lang.String.valueOf(_value);
  }

  public boolean equals(java.lang.Object obj) {
    if (obj != null) {
      if (obj instanceof WsdlStyleType) {
        if (_value.equals(((WsdlStyleType)obj)._value)) {
          return true;
        }
      }
    }
    return false;
  }

  public int hashCode() {
    return this._value.hashCode();
  }

}
