/*
 * Generated by SAP SchemaToJava Generator NW05 on Fri Jun 01 12:58:39 EEST 2007
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.services.webservices.server.deploy.descriptors.ws;

/**
 * Schema complexType Java representation.
 * Represents type {http://www.sap.com/webas/710/ws/webservices-j2ee-engine-descriptor}wsdlType
 */
public  class WsdlType implements java.io.Serializable {

  private static final long serialVersionUID = 4546027560217864432L;

  // Attribute field for attribute {}type
  private com.sap.engine.services.webservices.server.deploy.descriptors.ws.WsdlTypeType _a_Type;
  /**
   * Set method for attribute {}type
   */
  public void setType(com.sap.engine.services.webservices.server.deploy.descriptors.ws.WsdlTypeType _Type) {
    this._a_Type = _Type;
  }
  /**
   * Get method for attribute {}type
   */
  public com.sap.engine.services.webservices.server.deploy.descriptors.ws.WsdlTypeType getType() {
    return _a_Type;
  }

  // Attribute field for attribute {}style
  private com.sap.engine.services.webservices.server.deploy.descriptors.ws.WsdlStyleType _a_Style;
  /**
   * Set method for attribute {}style
   */
  public void setStyle(com.sap.engine.services.webservices.server.deploy.descriptors.ws.WsdlStyleType _Style) {
    this._a_Style = _Style;
  }
  /**
   * Get method for attribute {}style
   */
  public com.sap.engine.services.webservices.server.deploy.descriptors.ws.WsdlStyleType getStyle() {
    return _a_Style;
  }

  // Simple content field
  private java.lang.String _f__value;
  /**
   * Set method for simple content.
   */
  public void set_value(java.lang.String __value) {
    this._f__value = __value;
  }
  /**
   * Get method for simple content.
   */
  public java.lang.String get_value() {
    return this._f__value;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof WsdlType)) return false;
    WsdlType typed = (WsdlType) object;
    if (this._a_Type != null) {
      if (typed._a_Type == null) return false;
      if (!this._a_Type.equals(typed._a_Type)) return false;
    } else {
      if (typed._a_Type != null) return false;
    }
    if (this._a_Style != null) {
      if (typed._a_Style == null) return false;
      if (!this._a_Style.equals(typed._a_Style)) return false;
    } else {
      if (typed._a_Style != null) return false;
    }
    if (this._f__value != null) {
      if (typed._f__value == null) return false;
      if (!this._f__value.equals(typed._f__value)) return false;
    } else {
      if (typed._f__value != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._a_Type != null) {
      result+= this._a_Type.hashCode();
    }
    if (this._a_Style != null) {
      result+= this._a_Style.hashCode();
    }
    if (this._f__value != null) {
      result+= this._f__value.hashCode();
    }
    return result;
  }
}
