/*
 * Generated by SAP SchemaToJava Generator NW05 on Fri May 26 15:19:50 EEST 2006
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.services.webservices.espbase.configuration.relations;

/**
 * Schema complexType Java representation.
 * Represents type {http://www.sap.com/webas/710/ws/property-relations}DependencyEntityType
 */
public  class DependencyEntityType implements java.io.Serializable {

  // Attribute field for attribute {}id
  private java.lang.Integer _a_Id;
  /**
   * Set method for attribute {}id
   */
  public void setId(java.lang.Integer _Id) {
    this._a_Id = _Id;
  }
  /**
   * Get method for attribute {}id
   */
  public java.lang.Integer getId() {
    return _a_Id;
  }

  // Element field for element {}condition-properties
  private com.sap.engine.services.webservices.espbase.configuration.relations.PropertyListType _f_ConditionProperties;
  /**
   * Set method for element {}condition-properties
   */
  public void setConditionProperties(com.sap.engine.services.webservices.espbase.configuration.relations.PropertyListType _ConditionProperties) {
    this._f_ConditionProperties = _ConditionProperties;
  }
  /**
   * Get method for element {}condition-properties
   */
  public com.sap.engine.services.webservices.espbase.configuration.relations.PropertyListType getConditionProperties() {
    return this._f_ConditionProperties;
  }

  // Element field for element {}dependency
  private com.sap.engine.services.webservices.espbase.configuration.relations.DependencyType _f_Dependency;
  /**
   * Set method for element {}dependency
   */
  public void setDependency(com.sap.engine.services.webservices.espbase.configuration.relations.DependencyType _Dependency) {
    this._f_Dependency = _Dependency;
  }
  /**
   * Get method for element {}dependency
   */
  public com.sap.engine.services.webservices.espbase.configuration.relations.DependencyType getDependency() {
    return this._f_Dependency;
  }

  /**
   * Equals method implementation.
   */
  public boolean equals(Object object) {
    if (object == null) return false;
    if (!(object instanceof DependencyEntityType)) return false;
    DependencyEntityType typed = (DependencyEntityType) object;
    if (this._a_Id != null) {
      if (typed._a_Id == null) return false;
      if (!this._a_Id.equals(typed._a_Id)) return false;
    } else {
      if (typed._a_Id != null) return false;
    }
    if (this._f_ConditionProperties != null) {
      if (typed._f_ConditionProperties == null) return false;
      if (!this._f_ConditionProperties.equals(typed._f_ConditionProperties)) return false;
    } else {
      if (typed._f_ConditionProperties != null) return false;
    }
    if (this._f_Dependency != null) {
      if (typed._f_Dependency == null) return false;
      if (!this._f_Dependency.equals(typed._f_Dependency)) return false;
    } else {
      if (typed._f_Dependency != null) return false;
    }
    return true;
  }

  /**
   * Hashcode method implementation.
   */
  public int hashCode() {
    int result = 0;
    if (this._a_Id != null) {
      result+= this._a_Id.hashCode();
    }
    if (this._f_ConditionProperties != null) {
      result+= this._f_ConditionProperties.hashCode();
    }
    if (this._f_Dependency != null) {
      result+= this._f_Dependency.hashCode();
    }
    return result;
  }
}
