
/*
This file is generated by Code Generator
for CIMClass SAP_ITSAMArchSessionAccessor
WARNING:DO NOT CHANGE THE CODE MANUALLY
*/

package com.sap.archtech.archconn.mbeans;	

import java.util.Date;
import javax.management.ObjectName;


/* 
ManagedElement is an abstract class that provides a common superclass (or top of the inheritance tree) for the non-association classes in the CIM Schema. 
@version  1.0	
*/	


public interface SAP_ITSAMArchSessionAccessor{

public com.sap.archtech.archconn.mbeans.SAP_ITSAMArchSession getSessionForDeletion(String collURI);

public com.sap.archtech.archconn.mbeans.SAP_ITSAMArchSession[] getSessionsForDeletion(String archSetName);

public com.sap.archtech.archconn.mbeans.SAP_ITSAMArchSession[] getMonitoredSessions(String archSetName);

public com.sap.archtech.archconn.mbeans.SAP_ITSAMArchSession[] getBrokenWriteSessions(String archSetName);

public com.sap.archtech.archconn.mbeans.SAP_ITSAMArchSession[] getIncompleteSessions(String archSetName);

public String getSessionLog(String colUri);

public void startJobImmediately(byte[] jobParams , String archSetName , boolean isWriteJob , byte[] uiLocale);

public void startCronJob(byte[] jobParams , String archSetName , byte[] scheduleTime , boolean isWriteJob , byte[] uiLocale);

public void markForCancellation(String archSetName , String collURI);

public boolean isJobParamAvailable(String archSetName , String jobParamName);
	
	}