

/*
This file is generated by Code Generator
for CIMClass SAP_ITSAMArchSetProp
WARNING:DO NOT CHANGE THE CODE MANUALLY
*/

package com.sap.archtech.archconn.mbeans;	

import java.util.Date;
/* 
ManagedElement is an abstract class that provides a common superclass (or top of the inheritance tree) for the non-association classes in the CIM Schema. 
@version 1.0	
*/	

public class SAP_ITSAMArchSetProp{

private String archSetName=null;
	
private String propertyName=null;
	
private String propertyValue=null;
	
private String propertyShortText=null;
	
private int propertyPosition=0;
	
public SAP_ITSAMArchSetProp(){

}

/*

@return String
*/
public String getarchSetName() 
{
return this.archSetName;
}

/*
@param String
*/
public void setarchSetName(String archSetName)
{
this.archSetName = archSetName;
}

/*

@return String
*/
public String getpropertyName() 
{
return this.propertyName;
}

/*
@param String
*/
public void setpropertyName(String propertyName)
{
this.propertyName = propertyName;
}

/*

@return String
*/
public String getpropertyValue() 
{
return this.propertyValue;
}

/*
@param String
*/
public void setpropertyValue(String propertyValue)
{
this.propertyValue = propertyValue;
}

/*

@return String
*/
public String getpropertyShortText() 
{
return this.propertyShortText;
}

/*
@param String
*/
public void setpropertyShortText(String propertyShortText)
{
this.propertyShortText = propertyShortText;
}

/*

@return int
*/
public int getpropertyPosition()
{
return this.propertyPosition;
}

/*
@param int
*/
public void setpropertyPosition(int propertyPosition)
{
this.propertyPosition = propertyPosition;
}
	
}
