
/*
This file is generated by Code Generator
for CIMClass SAP_ITSAMArchSelParmAccessor
WARNING:DO NOT CHANGE THE CODE MANUALLY
*/

package com.sap.archtech.archconn.mbeans;	

import javax.management.ObjectName;

/* 
ManagedElement is an abstract class that provides a common superclass (or top of the inheritance tree) for the non-association classes in the CIM Schema. 
@version  1.0	
*/	


public interface SAP_ITSAMArchSelParmAccessor{

public com.sap.archtech.archconn.mbeans.SAP_ITSAMArchSelParm[] getArchSetSelParams(String archSetName , byte[] uiLocale);

public boolean isJobDefinitionAvailable(String archSetName);
	
	}