package com.sap.sapcontrol.client;

/**
 * Service Interface (generated by SAP WSDL to Java generator).
 */
public interface SAPControl extends javax.xml.rpc.Service {

  public com.sap.sapcontrol.client.SAPControlPortType getSAPControl() throws javax.xml.rpc.ServiceException;


  public java.rmi.Remote getLogicalPort(java.lang.Class seiClass) throws javax.xml.rpc.ServiceException;

  public java.rmi.Remote getLogicalPort(java.lang.String portName, java.lang.Class className) throws javax.xml.rpc.ServiceException;

  public java.lang.String[] getLogicalPortNames();

  public com.sap.sapcontrol.client.SAPControlPortType getLogicalPort() throws javax.xml.rpc.ServiceException;

  public com.sap.sapcontrol.client.SAPControlPortType getLogicalPort(java.lang.String portName) throws javax.xml.rpc.ServiceException;

}
