package com.sap.sapcontrol.client;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
public interface SAPControlPortType extends java.rmi.Remote,javax.xml.rpc.Stub {

  /**
   * Java representation of web method [Start].
   */
  public void start() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [Stop].
   */
  public void stop() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [Shutdown].
   */
  public void shutdown() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [ParameterValue].
   */
  public java.lang.String parameterValue(java.lang.String parameter) throws java.rmi.RemoteException;

  /**
   * Java representation of web method [GetProcessList].
   */
  public com.sap.sapcontrol.client.types.ArrayOfOSProcess getProcessList() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [GetStartProfile].
   */
  public void getStartProfile(javax.xml.rpc.holders.StringHolder name, com.sap.sapcontrol.client.holders.ArrayOfStringHolder lines) throws java.rmi.RemoteException;

  /**
   * Java representation of web method [GetTraceFile].
   */
  public void getTraceFile(javax.xml.rpc.holders.StringHolder name, com.sap.sapcontrol.client.holders.ArrayOfStringHolder lines) throws java.rmi.RemoteException;

  /**
   * Java representation of web method [GetAlertTree].
   */
  public com.sap.sapcontrol.client.types.ArrayOfAlertNode getAlertTree() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [GetAlerts].
   */
  public void getAlerts(java.lang.String rootTid, javax.xml.rpc.holders.StringHolder rootTidName, com.sap.sapcontrol.client.holders.ArrayOfAlertHolder alert) throws java.rmi.RemoteException;

  /**
   * Java representation of web method [RestartService].
   */
  public void restartService() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [StopService].
   */
  public void stopService() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [GetEnvironment].
   */
  public com.sap.sapcontrol.client.types.ArrayOfString getEnvironment() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [ListDeveloperTraces].
   */
  public com.sap.sapcontrol.client.types.ArrayOfDirEntry listDeveloperTraces() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [ReadDeveloperTrace].
   */
  public void readDeveloperTrace(java.lang.String filename, int size, javax.xml.rpc.holders.StringHolder name, com.sap.sapcontrol.client.holders.ArrayOfStringHolder lines) throws java.rmi.RemoteException;

  /**
   * Java representation of web method [RestartInstance].
   */
  public void restartInstance() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [SendSignal].
   */
  public void sendSignal(int pid, java.lang.String signal) throws java.rmi.RemoteException;

  /**
   * Java representation of web method [GetVersionInfo].
   */
  public com.sap.sapcontrol.client.types.ArrayOfInstanceVersionInfo getVersionInfo() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [GetQueueStatistic].
   */
  public com.sap.sapcontrol.client.types.ArrayOfTaskHandlerQueue getQueueStatistic() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [GetInstanceProperties].
   */
  public com.sap.sapcontrol.client.types.ArrayOfInstanceProperties getInstanceProperties() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [OSExecute].
   */
  public void OSExecute(java.lang.String command, int async, int timeout, java.lang.String protocolfile, javax.xml.rpc.holders.IntHolder exitcode, javax.xml.rpc.holders.IntHolder pid, com.sap.sapcontrol.client.holders.ArrayOfStringHolder lines) throws java.rmi.RemoteException;

  /**
   * Java representation of web method [ReadLogFile].
   */
  public void readLogFile(java.lang.String filename, java.lang.String filter, java.lang.String language, int maxentries, java.lang.String statecookie, javax.xml.rpc.holders.StringHolder format, javax.xml.rpc.holders.StringHolder startcookie, javax.xml.rpc.holders.StringHolder endcookie, com.sap.sapcontrol.client.holders.ArrayOfStringHolder fields) throws java.rmi.RemoteException;

  /**
   * Java representation of web method [ListLogFiles].
   */
  public com.sap.sapcontrol.client.types.ArrayOfLogFile listLogFiles() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [GetAccessPointList].
   */
  public com.sap.sapcontrol.client.types.ArrayOfAccessPoint getAccessPointList() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [ABAPReadSyslog].
   */
  public com.sap.sapcontrol.client.types.ArrayOfSyslogEntry ABAPReadSyslog() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [ABAPReadRawSyslog].
   */
  public com.sap.sapcontrol.client.types.ArrayOfRawSyslogEntry ABAPReadRawSyslog() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [ABAPGetWPTable].
   */
  public com.sap.sapcontrol.client.types.ArrayOfWorkProcess ABAPGetWPTable() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [ABAPAcknowledgeAlerts].
   */
  public com.sap.sapcontrol.client.types.ArrayOfInt ABAPAcknowledgeAlerts(java.lang.String r3Client, java.lang.String r3User, java.lang.String r3Password, com.sap.sapcontrol.client.types.ArrayOfString aid) throws java.rmi.RemoteException;

  /**
   * Java representation of web method [J2EEGetProcessList].
   */
  public com.sap.sapcontrol.client.types.ArrayOfJ2EEProcess j2EEGetProcessList() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [J2EEControlProcess].
   */
  public void j2EEControlProcess(java.lang.String processname, java.lang.String function) throws java.rmi.RemoteException;

  /**
   * Java representation of web method [J2EEGetThreadList].
   */
  public com.sap.sapcontrol.client.types.ArrayOfJ2EEThread j2EEGetThreadList() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [J2EEGetSessionList].
   */
  public com.sap.sapcontrol.client.types.ArrayOfJ2EESession j2EEGetSessionList() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [J2EEGetWebSessionList].
   */
  public com.sap.sapcontrol.client.types.ArrayOfJ2EEWebSession j2EEGetWebSessionList() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [J2EEGetCacheStatistic].
   */
  public com.sap.sapcontrol.client.types.ArrayOfJ2EECache j2EEGetCacheStatistic() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [J2EEGetCacheStatistic2].
   */
  public com.sap.sapcontrol.client.types.ArrayOfJ2EECache2 j2EEGetCacheStatistic2() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [J2EEGetApplicationAliasList].
   */
  public com.sap.sapcontrol.client.types.ArrayOfJ2EEApplicationAlias j2EEGetApplicationAliasList() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [J2EEGetVMGCHistory].
   */
  public com.sap.sapcontrol.client.types.ArrayOfGCInfo j2EEGetVMGCHistory() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [J2EEGetVMGCHistory2].
   */
  public com.sap.sapcontrol.client.types.ArrayOfGCInfo2 j2EEGetVMGCHistory2() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [J2EEGetVMHeapInfo].
   */
  public com.sap.sapcontrol.client.types.ArrayOfHeapInfo j2EEGetVMHeapInfo() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [J2EEGetEJBSessionList].
   */
  public com.sap.sapcontrol.client.types.ArrayOfJ2EEEJBSession j2EEGetEJBSessionList() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [J2EEGetRemoteObjectList].
   */
  public com.sap.sapcontrol.client.types.ArrayOfJ2EERemoteObject j2EEGetRemoteObjectList() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [J2EEGetClusterMsgList].
   */
  public com.sap.sapcontrol.client.types.ArrayOfJ2EEClusterMsg j2EEGetClusterMsgList() throws java.rmi.RemoteException;

  /**
   * Java representation of web method [J2EEGetSharedTableInfo].
   */
  public com.sap.sapcontrol.client.types.ArrayOfJ2EESharedTableInfo j2EEGetSharedTableInfo() throws java.rmi.RemoteException;

}
