package org.spec.jappserver.mfg;

import com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl;

/**
 * Service implementation of {WorkOrderSesEJBService} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "WorkOrderSesEJBService", targetNamespace = "http://mfg.jappserver.spec.org/", wsdlLocation = "wsdl/wsdlroot_WorkOrderSesEJBService_WorkOrderSesEJB/wsdlroot.wsdl")
public class WorkOrderSesEJBService extends javax.xml.ws.Service {

  private final static java.net.URL WORKORDERSESEJBSERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = Thread.currentThread().getContextClassLoader().getResource("wsdl/wsdlroot_WorkOrderSesEJBService_WorkOrderSesEJB/wsdlroot.wsdl");
		
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    WORKORDERSESEJBSERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public WorkOrderSesEJBService() throws java.net.MalformedURLException {
    super(WORKORDERSESEJBSERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://mfg.jappserver.spec.org/", "WorkOrderSesEJBService"));
  }
  public WorkOrderSesEJBService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [WorkOrderSesEJBPort].
   */
  @javax.xml.ws.WebEndpoint(name = "WorkOrderSesEJBPort")
  public org.spec.jappserver.mfg.WorkOrderSesEJB getWorkOrderSesEJBPort() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://mfg.jappserver.spec.org/","WorkOrderSesEJBPort");
    return (org.spec.jappserver.mfg.WorkOrderSesEJB) super.getPort(portName,org.spec.jappserver.mfg.WorkOrderSesEJB.class);
  }
}
