/*
 * Generated by SAP SchemaToJava Generator NW05 on Wed Feb 20 16:00:14 EET 2008
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.services.webservices.server.deploy.descriptors.wsclients;

/**
 * Enumeration Java representation.
 * Represents type {http://www.sap.com/webas/710/wsclients/ws-clients-j2ee-engine-descriptor}implTypeType
 */
public class ImplTypeType implements java.io.Serializable {

  private static final long serialVersionUID = 8000860376886190038L;

  public static final java.lang.String _src = "src";
  public static final java.lang.String _bin = "bin";

  public static final ImplTypeType src = new ImplTypeType(_src);
  public static final ImplTypeType bin = new ImplTypeType(_bin);

  //  Enumeration Content
  protected java.lang.String _value;

  public ImplTypeType(java.lang.String _value) {
    if (_src.equals(_value)) {
      this._value = _value;
      return;
    }
    if (_bin.equals(_value)) {
      this._value = _value;
      return;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+_value+"] passed.");
  }

  public java.lang.String getValue() {
    return _value;
  }

  public static ImplTypeType fromValue(java.lang.String value) {
    if (_src.equals(value)) {
      return src;
    }
    if (_bin.equals(value)) {
      return bin;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+value+"] passed.");
  }

  public static ImplTypeType fromString(String value) {
    if ("src".equals(value)) {
      return src;
    }
    if ("bin".equals(value)) {
      return bin;
    }
    throw new IllegalArgumentException("Invalid Enumeration value ["+value+"] passed.");
  }

  public java.lang.String toString() {
    if (_src.equals(_value)) {
      return "src";
    }
    if (_bin.equals(_value)) {
      return "bin";
    }
    return java.lang.String.valueOf(_value);
  }

  public boolean equals(java.lang.Object obj) {
    if (obj != null) {
      if (obj instanceof ImplTypeType) {
        if (_value.equals(((ImplTypeType)obj)._value)) {
          return true;
        }
      }
    }
    return false;
  }

  public int hashCode() {
    return this._value.hashCode();
  }

}
