/*
 * Generated by SAP SchemaToJava Generator NW05 on Mon May 21 11:37:23 EEST 2007
 * Copyright (c) 2002 by SAP Labs Sofia AG.
 * url: http://www.saplabs.bg
 * All rights reserved.
 */
package com.sap.engine.services.webservices.espbase.sr.metadata.frm;

/**
 * Schema complexType Java representation.
 * Represents type of namespace {http://www.sap.com/webas/2006/11/sr/metadata} anonymous with xpath [/xs:schema/xs:element/xs:complexType]
 */
public  class ClassificationsMetaDataSD extends com.sap.engine.services.webservices.jaxrpc.encoding.GeneratedComplexType {

  public java.lang.String _d_originalUri() {
    return "http://www.sap.com/webas/2006/11/sr/metadata";
  }

  public java.lang.String _d_originalLocalName() {
    return "";
  }

  private static com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[] ATTRIBUTEINFO;

  private synchronized static void initAttribs() {
    // Creating attribute fields
    if (ATTRIBUTEINFO != null) return;
    ATTRIBUTEINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[1];
    ATTRIBUTEINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo();
    // Attribute 0
    ATTRIBUTEINFO[0].fieldLocalName = "version";
    ATTRIBUTEINFO[0].fieldUri = "";
    ATTRIBUTEINFO[0].fieldJavaName = "Version";
    ATTRIBUTEINFO[0].typeName = "/xs:schema/xs:element/xs:complexType/xs:attribute/xs:simpleType";
    ATTRIBUTEINFO[0].typeUri = "http://www.sap.com/webas/2006/11/sr/metadata";
    ATTRIBUTEINFO[0].typeJavaName = "com.sap.engine.services.webservices.espbase.sr.metadata.Version";
    ATTRIBUTEINFO[0].defaultValue = null;
    ATTRIBUTEINFO[0].required = true;
    ATTRIBUTEINFO[0].setterMethod = "setVersion";
    ATTRIBUTEINFO[0].getterMethod = "getVersion";
    ATTRIBUTEINFO[0].checkMethod = null;
  }

  // Field information
  private static com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] FIELDINFO;

  private synchronized static void initFields() {
    // Creating fields
    if (FIELDINFO != null) return;
    FIELDINFO = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[1];
    FIELDINFO[0] = new com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo();
    // Field 0
    FIELDINFO[0].defaultValue = null;
    FIELDINFO[0].fieldJavaName = "ClassificationSystemsMetaData";
    FIELDINFO[0].fieldLocalName = "ClassificationSystemsMetaData";
    FIELDINFO[0].fieldModel = 1;
    FIELDINFO[0].fieldUri = "http://www.sap.com/webas/2006/11/sr/metadata";
    FIELDINFO[0].isSoapArray = false;
    FIELDINFO[0].maxOccurs = 1;
    FIELDINFO[0].minOccurs = 1;
    FIELDINFO[0].nillable = false;
    FIELDINFO[0].soapArrayDimensions = 0;
    FIELDINFO[0].soapArrayItemTypeJavaName = null;
    FIELDINFO[0].soapArrayItemTypeLocalName = null;
    FIELDINFO[0].soapArrayItemTypeUri = null;
    FIELDINFO[0].typeJavaName = "com.sap.engine.services.webservices.espbase.sr.metadata.ClassificationSystemsMetaData";
    FIELDINFO[0].typeLocalName = "ClassificationSystemsMetaData";
    FIELDINFO[0].typeUri = "http://www.sap.com/webas/2006/11/sr/metadata";
    FIELDINFO[0].getterMethod = "getClassificationSystemsMetaData";
    FIELDINFO[0].setterMethod = "setClassificationSystemsMetaData";
    FIELDINFO[0].checkMethod = null;
  }


  // Returns model Group Type
  public int _getModelType() {
    return 3;
  }

  private static boolean init = false;
  public synchronized com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] _getFields() {
    if (init == false) {
      com.sap.engine.services.webservices.jaxrpc.encoding.FieldInfo[] parent = super._getFields();
      FIELDINFO =  _insertFieldInfo(parent,FIELDINFO);
      init = true;
    }
    return FIELDINFO;
  }

  public int _getNumberOfFields() {
    return (FIELDINFO.length+super._getNumberOfFields());
  }

  public com.sap.engine.services.webservices.jaxrpc.encoding.AttributeInfo[] _getAttributes() {
    return ATTRIBUTEINFO;
  }

  public int _getNumberOfAttributes() {
    return ATTRIBUTEINFO.length;
  }

  static {
    initFields();
    initAttribs();
  }
}
